import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronRight, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { formatIDR } from '@/lib/format';

type CaseRow = { id:string; order_id:string; employer_id:string; worker_id:string|null; category:string; description:string; disputed_amount:number; requested_resolution:string|null; status:string; created_at:string; resolved_at:string|null };
const labels:Record<string,string>={payment:'Pembayaran',work_quality:'Kualitas pekerjaan',work_incomplete:'Pekerjaan tidak selesai',worker_no_show:'Mitra tidak datang',employer_cancelled:'Pembatalan employer',attendance:'Kehadiran / waktu kerja',safety:'Keselamatan',other:'Lainnya'};
const statuses=['open','waiting_response','under_review','waiting_evidence','negotiation','resolved','rejected','cancelled'];

export default function AdminResolutionQueue(){
 const [rows,setRows]=useState<CaseRow[]>([]); const [selected,setSelected]=useState<CaseRow|null>(null); const [status,setStatus]=useState('all'); const [decision,setDecision]=useState('no_change'); const [amount,setAmount]=useState('0'); const [rationale,setRationale]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 const load=useCallback(async()=>{setError(''); const {data,error:e}=await supabase.from('resolutions').select('id,order_id,employer_id,worker_id,category,description,disputed_amount,requested_resolution,status,created_at,resolved_at').order('created_at',{ascending:false}).limit(100); if(e)setError('Gagal memuat queue resolusi.'); else setRows((data??[]) as CaseRow[]);},[]);
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>status==='all'?rows:rows.filter(r=>r.status===status),[rows,status]);
 const decide=async()=>{if(!selected)return; const n=Number(amount)||0; if(rationale.trim().length<10){setError('Alasan keputusan minimal 10 karakter.');return;} if(['refund_employer','pay_worker','partial_settlement'].includes(decision)&&(n<=0||n>Number(selected.disputed_amount))){setError('Nominal keputusan harus lebih dari 0 dan tidak melebihi nominal sengketa.');return;} setBusy(true);setError(''); const {error:e}=await supabase.rpc('admin_decide_resolution',{p_resolution_id:selected.id,p_decision:decision,p_amount:n,p_rationale:rationale.trim()}); if(e)setError(e.message); else {setNotice('Keputusan resolusi berhasil dicatat.');setSelected(null);setRationale('');setAmount('0');await load();} setBusy(false);};
 return <div className="min-h-screen bg-slate-50 p-4 text-slate-900 sm:p-6"><div className="mx-auto max-w-7xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h1 className="text-xl font-extrabold">Resolution Command Queue</h1></div><p className="mt-1 text-xs text-slate-500">Case sengketa order · hanya Administrator yang dapat memutuskan.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-bold ring-1 ring-slate-200"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
 {notice&&<div className="mb-4 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700">{notice}</div>}{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>}
 <div className="mb-4 flex flex-wrap gap-2">{['all',...statuses].map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${status===s?'bg-slate-900 text-white':'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{s==='all'?'Semua':s}</button>)}</div>
 <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="space-y-2">{filtered.length===0?<div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500 ring-1 ring-slate-200">Tidak ada kasus pada filter ini.</div>:filtered.map(r=><button key={r.id} onClick={()=>{setSelected(r);setDecision('no_change');setAmount(String(Number(r.disputed_amount)||0));setRationale('')}} className={`w-full rounded-2xl bg-white p-4 text-left ring-1 ${selected?.id===r.id?'ring-slate-900':'ring-slate-200'}`}><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-extrabold">{labels[r.category]||r.category}</div><div className="mt-1 text-[11px] text-slate-500">Order {r.order_id.slice(0,8)}… · {new Date(r.created_at).toLocaleString('id-ID')}</div></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{r.status}</span></div><p className="mt-2 line-clamp-2 text-xs text-slate-600">{r.description}</p>{Number(r.disputed_amount)>0&&<div className="mt-2 text-xs font-bold">Sengketa {formatIDR(Number(r.disputed_amount))}</div>}<ChevronRight className="mt-2 ml-auto h-4 w-4 text-slate-400"/></button>)}</section>
 <aside className="h-fit rounded-2xl bg-white p-5 ring-1 ring-slate-200 lg:sticky lg:top-5">{!selected?<div className="py-10 text-center text-sm text-slate-500">Pilih kasus untuk memeriksa dan memutuskan.</div>:<><div className="flex items-start justify-between gap-3"><div><h2 className="font-extrabold">Detail kasus</h2><p className="mt-1 text-[11px] text-slate-500">{selected.id}</p></div><button onClick={()=>setSelected(null)} aria-label="Tutup" className="rounded-lg p-1"><XCircle className="h-5 w-5"/></button></div><div className="mt-4 space-y-3 text-xs"><div><b>Jenis:</b> {labels[selected.category]||selected.category}</div><div><b>Order:</b> {selected.order_id}</div><div><b>Status:</b> {selected.status}</div><div><b>Nominal sengketa:</b> {formatIDR(Number(selected.disputed_amount)||0)}</div><div><b>Deskripsi</b><p className="mt-1 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 leading-5">{selected.description}</p></div>{selected.requested_resolution&&<div><b>Permintaan pengguna</b><p className="mt-1 rounded-lg bg-slate-50 p-3">{selected.requested_resolution}</p></div>}</div><div className="mt-5 border-t pt-4"><label className="text-xs font-bold">Keputusan</label><select value={decision} onChange={e=>setDecision(e.target.value)} className="input mt-2 w-full"><option value="no_change">Tidak mengubah pembayaran</option><option value="pay_worker">Bayarkan ke mitra</option><option value="refund_employer">Refund employer</option><option value="partial_settlement">Settlement sebagian</option><option value="reject">Tolak kasus</option><option value="cancel">Batalkan kasus</option></select><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,''))} inputMode="numeric" className="input mt-2 w-full" placeholder="Nominal keputusan"/><textarea value={rationale} onChange={e=>setRationale(e.target.value.slice(0,5000))} maxLength={5000} rows={4} className="input mt-2 w-full" placeholder="Alasan keputusan minimal 10 karakter..."/><button disabled={busy} onClick={()=>void decide()} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>{busy?'Menyimpan...':'Tetapkan Keputusan'}</button></div></>}</aside></div></div></div>;
}
