import { useCallback, useEffect, useState } from 'react';
import { RefreshCw, ShieldCheck } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';

type Row={id:string;user_id:string;request_type:string;reason:string|null;status:string;created_at:string;resolved_at:string|null;resolution_note:string|null};
const label:Record<string,string>={access:'Akses data',correction:'Koreksi data',deletion:'Penghapusan data'};
export default function AdminPrivacyQueue(){const{user,profile}=useAuth();const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=useCallback(async()=>{if(!user)return;const{data,error:e}=await supabase.from('privacy_requests').select('id,user_id,request_type,reason,status,created_at,resolved_at,resolution_note').order('created_at',{ascending:false}).limit(100);if(e)setError(e.message);else setRows((data??[]) as Row[])},[user]);useEffect(()=>{void load()},[load]);
 const update=async(row:Row,status:'under_review'|'completed'|'rejected')=>{setBusy(row.id);setError('');setNotice('');const note=window.prompt('Catatan penyelesaian (opsional):',row.resolution_note??'');if(note===null){setBusy(null);return}const{error:e}=await supabase.from('privacy_requests').update({status,resolved_at:status==='completed'||status==='rejected'?new Date().toISOString():null,resolved_by:status==='completed'||status==='rejected'?user?.id:null,resolution_note:note.trim()||null}).eq('id',row.id);if(e)setError(e.message);else{setNotice('Status permintaan diperbarui.');await load()}setBusy(null)};
 if(!user||!profile)return null;if(profile.role!=='admin')return <div className="min-h-screen grid place-items-center p-6"><p>Akses admin ditolak.</p></div>;
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-5xl"><div className="mb-5 flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h1 className="text-xl font-extrabold">Privacy Review Queue</h1></div><p className="mt-1 text-xs text-slate-500">Review manusia untuk permintaan akses, koreksi, dan penghapusan data.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{error&&<div className="mb-4 rounded-lg bg-error-50 p-3 text-sm font-semibold text-error-700">{error}</div>}{notice&&<div className="mb-4 rounded-lg bg-success-50 p-3 text-sm font-semibold text-success-700">{notice}</div>}<div className="space-y-3">{rows.length===0?<div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500 ring-1 ring-slate-200">Belum ada permintaan.</div>:rows.map(r=><div key={r.id} className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{label[r.request_type]||r.request_type}</p><p className="mt-1 text-xs text-slate-500">User {r.user_id.slice(0,8)}… · {new Date(r.created_at).toLocaleString('id-ID')}</p>{r.reason&&<p className="mt-2 text-sm text-slate-700">{r.reason}</p>}</div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold">{r.status}</span></div>{r.resolution_note&&<p className="mt-2 text-xs text-slate-500">Catatan: {r.resolution_note}</p>}<div className="mt-3 flex flex-wrap gap-2">{r.status==='open'&&<button disabled={busy===r.id} onClick={()=>void update(r,'under_review')} className="rounded-lg border px-3 py-2 text-xs font-bold">Mulai Review</button>}{['open','under_review'].includes(r.status)&&<><button disabled={busy===r.id} onClick={()=>void update(r,'completed')} className="rounded-lg bg-success-600 px-3 py-2 text-xs font-bold text-white">Selesaikan</button><button disabled={busy===r.id} onClick={()=>void update(r,'rejected')} className="rounded-lg border border-error-200 px-3 py-2 text-xs font-bold text-error-700">Tolak</button></>}</div></div>)}</div></div></main>;
}
