import { useEffect, useState } from 'react';
import { ArrowLeft, DollarSign, FileText, LayoutDashboard, LogOut, RefreshCw, Save, Settings2, ShieldCheck } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import AdminKycReview from './AdminKycReview';
import AdminPricingReview from './AdminPricingReview';
import AdminPasskeySetup from './AdminPasskeySetup';
import type { View } from '@/lib/types';

type Row = { id:string; content_key:string; section:string; value_id:string; value_en:string; description:string|null };
type Tab = 'overview'|'content'|'kyc'|'pricing'|'security';

export default function AdminDashboard({ onNavigate }:{onNavigate:(view:View)=>void}) {
  const { user, profile, signOut } = useAuth();
  const [tab,setTab]=useState<Tab>('overview'); const [rows,setRows]=useState<Row[]>([]); const [drafts,setDrafts]=useState<Record<string,{id:string;en:string}>>({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(''); const [notice,setNotice]=useState('');
  const load=async()=>{setLoading(true);const {data}=await supabase.from('site_content').select('id,content_key,section,value_id,value_en,description').order('section').order('content_key');if(data){setRows(data as Row[]);setDrafts(Object.fromEntries((data as Row[]).map(r=>[r.id,{id:r.value_id,en:r.value_en}])))}setLoading(false)};
  useEffect(()=>{void load()},[]);
  const save=async(r:Row)=>{const d=drafts[r.id];if(!d||!user)return;setSaving(r.id);const {error}=await supabase.from('site_content').update({value_id:d.id,value_en:d.en,updated_at:new Date().toISOString(),updated_by:user.id}).eq('id',r.id);setSaving('');setNotice(error?`Gagal: ${error.message}`:`Tersimpan: ${r.content_key}`);if(!error)await load()};
  const logout=async()=>{await signOut();onNavigate('landing')};
  const tabs:[Tab,string,typeof LayoutDashboard][]=[['overview','Dashboard',LayoutDashboard],['content','Konten & Layout',FileText],['kyc','KYC',ShieldCheck],['pricing','Harga & Timer',DollarSign],['security','Keamanan',Settings2]];
  return <div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="container-app flex min-h-16 items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-900 text-white"><Settings2 className="h-5 w-5"/></div><div><b className="text-sm">KerjaHarian Admin</b><div className="text-xs text-slate-500">{profile?.full_name??'Administrator'}</div></div></div><div className="flex gap-2"><button onClick={()=>onNavigate('landing')} className="hidden sm:inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ring-1 ring-slate-200"><ArrowLeft className="h-4 w-4"/>Kembali</button><button onClick={logout} className="inline-flex items-center gap-2 rounded-lg bg-error-50 px-3 py-2 text-sm font-semibold text-error-600 ring-1 ring-error-200"><LogOut className="h-4 w-4"/>Keluar</button></div></div></header><main className="container-app py-6"><div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-xl p-4 text-left text-sm font-bold ring-1 ${tab===id?'bg-slate-900 text-white ring-slate-900':'bg-white text-slate-700 ring-slate-200'}`}><Icon className="h-5 w-5"/>{label}</button>)}</div>
  {tab==='overview'&&<section className="space-y-5"><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><h1 className="text-2xl font-extrabold">Control Center</h1><p className="mt-1 text-sm text-slate-500">Pusat kontrol seluruh aplikasi KerjaHarian.</p></div><div className="grid gap-4 md:grid-cols-3">{[['landing','Beranda','Halaman publik utama'],['employer','Employer','Pesan tenaga kerja'],['worker','Mitra Pekerja','Pekerjaan, kehadiran dan timer']].map(([v,l,d])=><button key={v} onClick={()=>onNavigate(v as View)} className="rounded-xl bg-white p-5 text-left ring-1 ring-slate-200 hover:ring-slate-400"><b>{l}</b><p className="mt-2 text-sm text-slate-500">{d}</p></button>)}</div></section>}
  {tab==='content'&&<section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div className="mb-5 flex justify-between gap-3"><div><h2 className="text-xl font-extrabold">Konten & Layout</h2><p className="text-sm text-slate-500">Tulisan tersimpan di Supabase dan hanya dapat diubah admin.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm ring-1 ring-slate-200"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{notice&&<div className="mb-4 rounded-lg bg-slate-100 p-3 text-sm font-semibold">{notice}</div>}{loading?<p className="py-10 text-center text-sm text-slate-500">Memuat...</p>:rows.map(r=>{const d=drafts[r.id]??{id:r.value_id,en:r.value_en};return <div key={r.id} className="mb-4 rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between gap-3"><div><b className="text-sm">{r.content_key}</b><p className="text-xs text-slate-500">{r.description}</p></div><button disabled={saving===r.id} onClick={()=>void save(r)} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{saving===r.id?'Menyimpan...':<><Save className="h-3.5 w-3.5"/>Simpan</>}</button></div><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Indonesia<textarea className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm" value={d.id} onChange={e=>setDrafts(x=>({...x,[r.id]:{...d,id:e.target.value}}))}/></label><label className="text-xs font-bold">English<textarea className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm" value={d.en} onChange={e=>setDrafts(x=>({...x,[r.id]:{...d,en:e.target.value}}))}/></label></div></div>})}</section>}
  {tab==='kyc'&&<AdminKycReview/>}{tab==='pricing'&&<AdminPricingReview/>}{tab==='security'&&<AdminPasskeySetup/>}
 </main></div>;
}
