import { useEffect, useState } from 'react';
import { CheckCircle2, Eye, Loader2, ShieldCheck, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type KycRow = { id:string; full_name:string|null; role:string; phone:string|null; ktp_photo_url:string; kyc_verified:boolean; kyc_status:string; kyc_submitted_at:string|null; kyc_rejection_reason:string|null };

export default function AdminKycReview() {
  const [rows,setRows]=useState<KycRow[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState(''); const [selected,setSelected]=useState<string|null>(null); const [image,setImage]=useState<string|null>(null);
  const load=async()=>{setLoading(true);const r=await supabase.rpc('admin_list_kyc');if(r.error)setError(r.error.message);else setRows((r.data??[]) as KycRow[]);setLoading(false);};
  useEffect(()=>{load();},[]);
  const view=async(row:KycRow)=>{setSelected(row.id);setImage(null);const r=await supabase.storage.from('kyc-docs').createSignedUrl(row.ktp_photo_url,300);if(r.error)setError(r.error.message);else setImage(r.data.signedUrl);};
  const review=async(id:string,approve:boolean)=>{setBusy(id);setError('');const r=await supabase.rpc('admin_review_kyc',{p_user_id:id,p_approve:approve,p_rejection_reason:approve?null:'Foto KTP tidak memenuhi standar verifikasi.'});if(r.error)setError(r.error.message);else await load();setBusy(null);if(selected===id){setSelected(null);setImage(null);}};
  if(loading)return <div className="rounded-xl border bg-white p-6"><Loader2 className="h-5 w-5 animate-spin"/></div>;
  return <section className="space-y-4 rounded-2xl border bg-white p-4 md:p-6"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h2 className="text-lg font-bold">Verifikasi KTP</h2></div><p className="mt-1 text-sm text-gray-600">Mitra dan Pemberi Kerja diperlakukan sama. Periksa foto KTP secara manual sebelum menyetujui.</p></div>{error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{rows.length===0?<p className="text-sm text-gray-500">Belum ada pengajuan KTP.</p>:rows.map(row=><div key={row.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{row.full_name||'Tanpa nama'}</p><p className="text-xs text-gray-500">{row.role==='worker'?'Mitra Pekerja':'Pemberi Kerja'} · {row.phone||'-'}</p><span className="mt-1 inline-block rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold">{row.kyc_status}</span></div><div className="flex flex-wrap gap-2"><button onClick={()=>view(row)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Eye className="h-4 w-4"/>Lihat KTP</button>{row.kyc_status==='pending'&&<><button disabled={busy===row.id} onClick={()=>review(row.id,true)} className="inline-flex items-center gap-2 rounded-lg bg-green-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>Setujui</button><button disabled={busy===row.id} onClick={()=>review(row.id,false)} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><XCircle className="h-4 w-4"/>Tolak</button></>}</div></div>{selected===row.id&&image&&<img src={image} alt="KTP pengguna" className="mt-4 max-h-[420px] w-full rounded-lg border object-contain"/>}</div>)}</section>;
}
