import { useEffect, useState } from 'react';
import { CheckCircle2, Eye, Loader2, ShieldCheck, UserRound, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type KycRow = { id:string; full_name:string|null; role:string; phone:string|null; ktp_photo_url:string; selfie_photo_url:string|null; kyc_verified:boolean; kyc_status:string; kyc_submitted_at:string|null; kyc_rejection_reason:string|null };

type Images = { ktp:string|null; selfie:string|null };

export default function AdminKycReview() {
  const [rows,setRows]=useState<KycRow[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState(''); const [selected,setSelected]=useState<string|null>(null); const [images,setImages]=useState<Images>({ktp:null,selfie:null});
  const load=async()=>{setLoading(true);const r=await supabase.rpc('admin_list_kyc');if(r.error)setError(r.error.message);else setRows((r.data??[]) as KycRow[]);setLoading(false);};
  useEffect(()=>{void load();},[]);
  const view=async(row:KycRow)=>{setSelected(row.id);setImages({ktp:null,selfie:null});setError('');const ktp=await supabase.storage.from('kyc-docs').createSignedUrl(row.ktp_photo_url,300);if(ktp.error){setError(ktp.error.message);return;}let selfie:string|null=null;if(row.role==='employer'&&row.selfie_photo_url){const s=await supabase.storage.from('kyc-docs').createSignedUrl(row.selfie_photo_url,300);if(s.error){setError(s.error.message);return;}selfie=s.data.signedUrl;}setImages({ktp:ktp.data.signedUrl,selfie});};
  const review=async(id:string,approve:boolean)=>{setBusy(id);setError('');const r=await supabase.rpc('admin_review_kyc',{p_user_id:id,p_approve:approve,p_rejection_reason:approve?null:'Dokumen KTP/selfie tidak memenuhi standar verifikasi.'});if(r.error)setError(r.error.message);else await load();setBusy(null);if(selected===id){setSelected(null);setImages({ktp:null,selfie:null});}};
  if(loading)return <div className="rounded-xl border bg-white p-6"><Loader2 className="h-5 w-5 animate-spin"/></div>;
  return <section className="space-y-4 rounded-2xl border bg-white p-4 md:p-6"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h2 className="text-lg font-bold">Verifikasi Identitas</h2></div><p className="mt-1 text-sm text-gray-600">Employer wajib diperiksa dengan KTP + selfie. Cocokkan wajah pada selfie dengan foto KTP sebelum menyetujui.</p></div>{error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{rows.length===0?<p className="text-sm text-gray-500">Belum ada pengajuan verifikasi.</p>:rows.map(row=><div key={row.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{row.full_name||'Tanpa nama'}</p><p className="text-xs text-gray-500">{row.role==='worker'?'Mitra Pekerja':'Pemberi Kerja'} · {row.phone||'-'}</p><span className="mt-1 inline-block rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold">{row.kyc_status}</span></div><div className="flex flex-wrap gap-2"><button onClick={()=>view(row)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Eye className="h-4 w-4"/>Lihat KTP</button>{row.role==='employer'&&<button onClick={()=>view(row)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><UserRound className="h-4 w-4"/>Lihat Selfie</button>}{row.kyc_status==='pending'&&<><button disabled={busy===row.id} onClick={()=>review(row.id,true)} className="inline-flex items-center gap-2 rounded-lg bg-green-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>Setujui</button><button disabled={busy===row.id} onClick={()=>review(row.id,false)} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><XCircle className="h-4 w-4"/>Tolak</button></>}</div></div>{selected===row.id&&images.ktp&&<div className="mt-4 grid gap-4 md:grid-cols-2"><div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-gray-500">KTP</p><img src={images.ktp} alt="KTP pengguna" className="max-h-[420px] w-full rounded-lg border object-contain"/></div>{row.role==='employer'&&<div><p className="mb-2 flex items-center gap-1 text-xs font-bold uppercase tracking-wide text-gray-500"><UserRound className="h-3.5 w-3.5"/>Selfie</p>{images.selfie?<img src={images.selfie} alt="Selfie Employer" className="max-h-[420px] w-full rounded-lg border object-contain"/>:<p className="rounded-lg bg-red-50 p-4 text-sm font-semibold text-red-700">Selfie belum tersedia.</p>}</div>}</div>}</div>)}</section>;
}
