import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, CheckCircle2, Clock3, DollarSign, FileText, LogOut, MapPin, RefreshCw, Save, Settings2, ShieldCheck, Users, BriefcaseBusiness, Radio, AlertTriangle, Trash2, BarChart3, Scale, type LucideIcon } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import AdminKycReview from './AdminKycReview';
import AdminPricingReview from './AdminPricingReview';
import AdminPasskeySetup from './AdminPasskeySetup';
import MarketplaceKpiPanel from './MarketplaceKpiPanel';
import AdminResolutionQueue from './AdminResolutionQueue';
import type { View } from '@/lib/types';

type Row = { id:string; content_key:string; section:string; value_id:string; value_en:string; description:string|null };
type Tab = 'overview'|'analytics'|'orders'|'people'|'content'|'kyc'|'pricing'|'resolution'|'security';
type Counts = { workers:number; employers:number; open:number; assigned:number; active:number; completed:number; pendingKyc:number; reports:number };
type RecentJob = { id:string; title:string; location:string|null; wage:number|null; status:string|null; workflow_status:string|null; created_at:string; started_at:string|null; overtime_minutes:number|null; overtime_amount:number|null; order_id:string|null };
const emptyCounts:Counts={workers:0,employers:0,open:0,assigned:0,active:0,completed:0,pendingKyc:0,reports:0};
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);

export default function AdminDashboard({ onNavigate }:{onNavigate:(view:View)=>void}) {
  const { user, profile, signOut } = useAuth();
  const [tab,setTab]=useState<Tab>('overview');
  const [rows,setRows]=useState<Row[]>([]);
  const [drafts,setDrafts]=useState<Record<string,{id:string;en:string}>>({});
  const [loading,setLoading]=useState(true); const [opsLoading,setOpsLoading]=useState(true);
  const [saving,setSaving]=useState(''); const [notice,setNotice]=useState(''); const [deleting,setDeleting]=useState<string|null>(null);
  const [counts,setCounts]=useState<Counts>(emptyCounts); const [recentJobs,setRecentJobs]=useState<RecentJob[]>([]);

  const loadContent=async()=>{setLoading(true);const {data,error}=await supabase.from('site_content').select('id,content_key,section,value_id,value_en,description').order('section').order('content_key');if(error){setNotice(`Gagal memuat CMS: ${error.message}`)}else if(data){const typed=data as Row[];setRows(typed);setDrafts(Object.fromEntries(typed.map(r=>[r.id,{id:r.value_id,en:r.value_en}])))}setLoading(false)};
  const loadOperations=async()=>{setOpsLoading(true);
    const [workers,employers,open,assigned,active,completed,pendingKyc,reports,recent]=await Promise.all([
      supabase.from('profiles').select('id',{count:'exact',head:true}).eq('role','worker'),
      supabase.from('profiles').select('id',{count:'exact',head:true}).eq('role','employer'),
      supabase.from('jobs').select('id',{count:'exact',head:true}).eq('status','open').eq('is_deleted',false),
      supabase.from('jobs').select('id',{count:'exact',head:true}).eq('status','assigned').eq('is_deleted',false),
      supabase.from('jobs').select('id',{count:'exact',head:true}).eq('workflow_status','active').eq('is_deleted',false),
      supabase.from('jobs').select('id',{count:'exact',head:true}).eq('status','completed').eq('is_deleted',false),
      supabase.from('profiles').select('id',{count:'exact',head:true}).eq('kyc_status','pending'),
      supabase.from('job_reports').select('id',{count:'exact',head:true}),
      supabase.from('jobs').select('id,title,location,wage,status,workflow_status,created_at,started_at,overtime_minutes,overtime_amount,order_id').eq('is_deleted',false).order('created_at',{ascending:false}).limit(50)
    ]);
    const firstError=[workers,employers,open,assigned,active,completed,pendingKyc,reports,recent].find(x=>x.error)?.error;
    if(firstError) setNotice(`Gagal memuat data admin: ${firstError.message}`);
    setCounts({workers:workers.count??0,employers:employers.count??0,open:open.count??0,assigned:assigned.count??0,active:active.count??0,completed:completed.count??0,pendingKyc:pendingKyc.count??0,reports:reports.count??0});
    setRecentJobs((recent.data??[]) as RecentJob[]); setOpsLoading(false);
  };
  useEffect(()=>{void loadContent();void loadOperations()},[]);
  const deleteRunningOrder=async(job:RecentJob)=>{
    if(deleting) return;
    const ok=window.confirm(`Hapus order/pekerjaan ini secara permanen?\n\n${job.title}\nStatus: ${job.workflow_status??job.status??'-'}\n\nTindakan ini tidak dapat dibatalkan.`);
    if(!ok) return;
    setDeleting(job.id);setNotice('Menghapus order...');
    const {data,error}=await supabase.rpc('admin_delete_running_order',{p_job_id:job.id});
    if(error){setNotice(`Gagal menghapus: ${error.message}`)}else if(data?.success!==true){setNotice('Gagal menghapus: server tidak mengonfirmasi penghapusan.')}else{setNotice(`Order ${job.title} berhasil dihapus.`);await loadOperations()}
    setDeleting(null);
  };
  const save=async(r:Row)=>{const d=drafts[r.id];if(!d||!user)return;setSaving(r.id);const {error}=await supabase.from('site_content').update({value_id:d.id,value_en:d.en,updated_at:new Date().toISOString(),updated_by:user.id}).eq('id',r.id);setSaving('');setNotice(error?`Gagal: ${error.message}`:`Tersimpan: ${r.content_key}`);if(!error)await loadContent()};
  const logout=async()=>{await signOut();onNavigate('landing')};
  const nav:[Tab,string,LucideIcon][]=[['overview','Overview',Activity],['analytics','KPI & Analytics',BarChart3],['orders','Jobs & Dispatch',BriefcaseBusiness],['people','Workers & Employers',Users],['content','Konten & Layout',FileText],['kyc','KYC',ShieldCheck],['pricing','Harga & Timer',DollarSign],['resolution','Resolution Center',Scale],['security','Keamanan & Access',Settings2]];
  const overviewStats:[string,number,LucideIcon,string][]=[['Workers',counts.workers,Users,'Supply tenaga kerja'],['Employers',counts.employers,BriefcaseBusiness,'Demand pemberi kerja'],['Open jobs',counts.open,Radio,'Menunggu matching'],['Active jobs',counts.active,Activity,'Sedang berlangsung']];
  const attention=useMemo(()=>[
    {label:'Job mencari pekerja',value:counts.open,icon:Radio,tab:'orders' as Tab,critical:counts.open>0},
    {label:'Job sedang aktif',value:counts.active,icon:Clock3,tab:'orders' as Tab,critical:false},
    {label:'KYC menunggu review',value:counts.pendingKyc,icon:ShieldCheck,tab:'kyc' as Tab,critical:counts.pendingKyc>0},
    {label:'Laporan/insiden',value:counts.reports,icon:AlertTriangle,tab:'resolution' as Tab,critical:counts.reports>0}
  ],[counts]);

  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="container-app flex min-h-16 items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-900 text-white"><Settings2 className="h-5 w-5"/></div><div><b className="text-sm">KerjaHarian Command Center</b><div className="text-xs text-slate-500">{profile?.full_name??'Administrator'} · Operational Control</div></div></div><div className="flex gap-2"><button onClick={()=>onNavigate('landing')} className="hidden sm:inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ring-1 ring-slate-200"><ArrowLeft className="h-4 w-4"/>Kembali</button><button onClick={logout} className="inline-flex items-center gap-2 rounded-lg bg-error-50 px-3 py-2 text-sm font-semibold text-error-600 ring-1 ring-error-200"><LogOut className="h-4 w-4"/>Keluar</button></div></div></header>
    <main className="container-app py-6"><div className="grid gap-5 lg:grid-cols-[230px_1fr]">
      <aside className="h-fit rounded-2xl bg-white p-3 ring-1 ring-slate-200 lg:sticky lg:top-24"><div className="px-3 pb-3 pt-2 text-[11px] font-extrabold uppercase tracking-widest text-slate-400">Command Center</div>{nav.slice(0,4).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${tab===id?'bg-slate-900 text-white':'text-slate-700 hover:bg-slate-100'}`}><Icon className="h-4 w-4"/>{label}</button>)}<div className="px-3 pb-2 pt-4 text-[11px] font-extrabold uppercase tracking-widest text-slate-400">Management</div>{nav.slice(4).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${tab===id?'bg-slate-900 text-white':'text-slate-700 hover:bg-slate-100'}`}><Icon className="h-4 w-4"/>{label}</button>)}<button onClick={()=>{void loadOperations();void loadContent()}} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><RefreshCw className="h-3.5 w-3.5"/>Refresh data</button></aside>
      <section className="min-w-0">
        {notice&&<div className="mb-4 rounded-xl bg-white p-3 text-sm font-semibold ring-1 ring-slate-200">{notice}</div>}
        {tab==='overview'&&<section className="space-y-5"><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs font-bold"><span className="h-2 w-2 rounded-full bg-emerald-500"/>LIVE OPERATIONS</div><h1 className="text-2xl font-extrabold tracking-tight">Admin Control Center</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Satu pusat kendali untuk marketplace health, supply, demand, dispatch, trust, resolution, pricing, konten, dan keamanan.</p></div><button onClick={()=>void loadOperations()} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Sync</button></div></div>
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{overviewStats.map(([label,value,Icon,sub])=><div key={label} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-500">{label}</span><Icon className="h-5 w-5 text-slate-400"/></div><div className="mt-3 text-3xl font-black">{opsLoading?'—':value}</div><div className="mt-1 text-xs text-slate-500">{sub}</div></div>)}</div>
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{attention.map(({label,value,icon:Icon,tab:t,critical})=><button key={label} onClick={()=>setTab(t)} className={`rounded-2xl bg-white p-4 text-left ring-1 ${critical?'ring-amber-300':'ring-slate-200'}`}><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-500">{label}</span><Icon className="h-4 w-4"/></div><div className="mt-2 text-2xl font-black">{value}</div><div className="mt-1 text-xs text-slate-500">Klik untuk buka queue</div></button>)}</div>
          <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-extrabold">Live Job Board</h2><p className="text-xs text-slate-500">Lifecycle: open → assigned → check-in → active → overtime → completed.</p></div><button onClick={()=>setTab('orders')} className="text-xs font-bold underline">Kelola semua</button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr><th className="py-3 pr-3">Job</th><th className="py-3 pr-3">Lokasi</th><th className="py-3 pr-3">State</th><th className="py-3">Nilai</th></tr></thead><tbody>{recentJobs.length===0?<tr><td colSpan={4} className="py-8 text-center text-slate-500">Belum ada job.</td></tr>:recentJobs.slice(0,8).map(j=><tr key={j.id} className="border-b last:border-0"><td className="py-3 pr-3 font-bold">{j.title}</td><td className="py-3 pr-3"><span className="inline-flex max-w-40 items-center gap-1 truncate"><MapPin className="h-3.5 w-3.5"/>{j.location??'-'}</span></td><td className="py-3 pr-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold">{j.workflow_status??j.status}</span></td><td className="py-3 font-semibold">{money(j.wage??0)}</td></tr>)}</tbody></table></div></div><div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 className="font-extrabold">Operational principles</h2><div className="mt-4 space-y-3 text-sm"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0"/><div><b>Demand first</b><p className="text-xs text-slate-500">Job baru masuk queue sebelum dispatch.</p></div></div><div className="flex gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0"/><div><b>Nearest eligible supply</b><p className="text-xs text-slate-500">Matching mempertimbangkan kategori, status online, jarak, dan verifikasi.</p></div></div><div className="flex gap-3"><Clock3 className="mt-0.5 h-4 w-4 shrink-0"/><div><b>State machine</b><p className="text-xs text-slate-500">Setiap pekerjaan memiliki state dan timestamp yang dapat diaudit.</p></div></div><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><div><b>Trust before scale</b><p className="text-xs text-slate-500">KYC, attendance, laporan, dan payment dipisahkan dari UI CMS.</p></div></div></div></div></div>
        </section>}
        {tab==='analytics'&&<section className="rounded-2xl bg-white p-1 ring-1 ring-slate-200"><MarketplaceKpiPanel/></section>}
        {tab==='orders'&&<section className="space-y-4"><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold">Jobs & Dispatch</h2><p className="text-sm text-slate-500">Kelola queue termasuk penghapusan order yang sedang berjalan.</p></div><button onClick={()=>void loadOperations()} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Open',counts.open],['Assigned',counts.assigned],['Active',counts.active],['Completed',counts.completed],['Reports',counts.reports]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-white p-4 ring-1 ring-slate-200"><div className="text-xs font-bold text-slate-500">{l}</div><div className="mt-2 text-2xl font-black">{v}</div></div>)}</div><div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h3 className="font-extrabold">Dispatch queue</h3><p className="mt-1 text-xs text-slate-500">50 job terakhir. Hapus hanya saat operator benar-benar ingin menghilangkan job/order dari sistem.</p><div className="mt-4 space-y-2">{recentJobs.map(j=><div key={j.id} className="grid gap-3 rounded-xl border p-3 sm:grid-cols-[1fr_140px_130px_auto] sm:items-center"><div><b className="text-sm">{j.title}</b><div className="text-xs text-slate-500">{j.location??'-'} · {j.order_id?'Order linked':'No linked order'}</div></div><span className="text-xs font-bold">{j.workflow_status??j.status}</span><span className="text-sm font-bold">{money(j.wage??0)}</span><button onClick={()=>void deleteRunningOrder(j)} disabled={deleting!==null} className="inline-flex items-center justify-center gap-1.5 rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700 ring-1 ring-red-200 disabled:opacity-50"><Trash2 className="h-3.5 w-3.5"/>{deleting===j.id?'Menghapus...':'Hapus'}</button></div>)}{recentJobs.length===0&&<div className="py-8 text-center text-sm text-slate-500">Queue kosong.</div>}</div></div></section>}
        {tab==='people'&&<section className="space-y-4"><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><h2 className="text-xl font-extrabold">Workers & Employers</h2><p className="text-sm text-slate-500">Pisahkan supply dan demand agar operator dapat melihat keseimbangan marketplace.</p></div><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><Users className="h-6 w-6"/><div className="mt-3 text-3xl font-black">{counts.workers}</div><b>Workers / Mitra</b><p className="mt-1 text-xs text-slate-500">Pantau availability, kategori, rating, KYC, dan kapasitas supply.</p></div><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><BriefcaseBusiness className="h-6 w-6"/><div className="mt-3 text-3xl font-black">{counts.employers}</div><b>Employers</b><p className="mt-1 text-xs text-slate-500">Pantau demand, job creation, approval, dan payment readiness.</p></div></div></section>}
        {tab==='content'&&<section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div className="mb-5 flex justify-between gap-3"><div><h2 className="text-xl font-extrabold">Konten & Layout</h2><p className="text-sm text-slate-500">Copy yang terhubung ke CMS Supabase.</p></div><button onClick={()=>void loadContent()} className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm ring-1 ring-slate-200"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{loading?<p className="py-10 text-center text-sm text-slate-500">Memuat...</p>:rows.map(r=>{const d=drafts[r.id]??{id:r.value_id,en:r.value_en};return <div key={r.id} className="mb-4 rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between gap-3"><div><b className="text-sm">{r.content_key}</b><p className="text-xs text-slate-500">{r.description}</p></div><button disabled={saving===r.id} onClick={()=>void save(r)} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{saving===r.id?'Menyimpan...':<><Save className="h-3.5 w-3.5"/>Simpan</>}</button></div><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Indonesia<textarea className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm" value={d.id} onChange={e=>setDrafts(x=>({...x,[r.id]:{...d,id:e.target.value}}))}/></label><label className="text-xs font-bold">English<textarea className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm" value={d.en} onChange={e=>setDrafts(x=>({...x,[r.id]:{...d,en:e.target.value}}))}/></label></div></div>})}</section>}
        {tab==='kyc'&&<AdminKycReview/>}{tab==='pricing'&&<AdminPricingReview/>}{tab==='resolution'&&<section className="rounded-2xl bg-white p-1 ring-1 ring-slate-200"><AdminResolutionQueue/></section>}{tab==='security'&&<AdminPasskeySetup/>}
      </section></div></main></div>;
}
