import { useEffect, useRef, useState } from 'react';
import { Bot, Mic, MicOff, Volume2, VolumeX, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/lib/supabase';

type Role = 'worker' | 'employer' | 'admin' | null;
interface SpeechRecognitionResultLike { [index:number]: { [index:number]: { transcript:string } }; length:number }
interface SpeechRecognitionEventLike extends Event { results:SpeechRecognitionResultLike }
interface SpeechRecognitionLike { lang:string; interimResults:boolean; continuous:boolean; start:()=>void; stop:()=>void; abort:()=>void; onresult:((event:SpeechRecognitionEventLike)=>void)|null; onerror:((event:Event)=>void)|null; onend:(()=>void)|null }
interface WindowSpeech extends Window { SpeechRecognition?:new()=>SpeechRecognitionLike; webkitSpeechRecognition?:new()=>SpeechRecognitionLike }
interface Props { role:Role; profile:Profile|null; }
const clean=(text:string)=>text.replace(/\s+/g,' ').trim();
export function AIVoiceAssistant({role,profile}:Props){
 const [open,setOpen]=useState(false);const [listening,setListening]=useState(false);const [speaking,setSpeaking]=useState(false);const [busy,setBusy]=useState(false);const [text,setText]=useState('');const [answer,setAnswer]=useState('');const [error,setError]=useState('');const [voiceOn,setVoiceOn]=useState(true);
 const recognitionRef=useRef<SpeechRecognitionLike|null>(null);const finalRef=useRef('');
 const supported=typeof window!=='undefined'&&!!((window as WindowSpeech).SpeechRecognition||(window as WindowSpeech).webkitSpeechRecognition);
 useEffect(()=>()=>{recognitionRef.current?.abort();window.speechSynthesis?.cancel()},[]);
 const speak=(value:string)=>{if(!voiceOn||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(value);u.lang='id-ID';u.rate=.98;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(u)};
 const ask=async(raw=text)=>{const prompt=clean(raw);if(!prompt||busy)return;setBusy(true);setError('');setAnswer('');setText('');try{const token=(await supabase.auth.getSession()).data.session?.access_token;if(!token)throw new Error('Silakan masuk terlebih dahulu.');let endpoint='/api/ai-problem-solver';let body:any={message:prompt,role,isOnline:profile?.is_online};if(role==='admin'){endpoint='/api/ai-admin-voice';body={message:prompt}}else if(role==='employer'&&/(butuh|cari|pesan|booking|pekerja|orang|besok|pagi|jadwal)/i.test(prompt)){endpoint='/api/ai-task-parser';body={text:prompt}}const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data?.error||'AI tidak tersedia.');let result='';if(endpoint.endsWith('ai-task-parser')){const d=data?.draft;result=d?`Saya memahami kebutuhan Anda: ${d.title||'pekerjaan harian'}, kategori ${d.category||'belum ditentukan'}, lokasi ${d.location||'belum ditentukan'}, ${d.required_count||1} pekerja${d.estimated_hours?`, sekitar ${d.estimated_hours} jam`:''}. Ini masih draft dan belum membuat booking. Buka Cari Pekerja untuk meninjau dan mengonfirmasi.`:'Draft pekerjaan belum dapat dibuat.'}else result=String(data?.answer||'AI belum memberikan jawaban.');setAnswer(result);speak(result)}catch(e){const msg=e instanceof Error?e.message:'Terjadi kesalahan.';setError(msg);speak(msg)}finally{setBusy(false)}};
 const startListening=()=>{if(!supported){setError('Browser ini belum menyediakan input suara. Anda tetap dapat menggunakan kolom teks.');return}if(listening){recognitionRef.current?.stop();return}setError('');finalRef.current='';const W=window as WindowSpeech;const R=W.SpeechRecognition||W.webkitSpeechRecognition;if(!R)return;const r=new R();r.lang='id-ID';r.interimResults=false;r.continuous=false;r.onresult=e=>{let out='';for(let i=0;i<e.results.length;i++)out+=e.results[i]?.[0]?.transcript||'';finalRef.current=clean(out);setText(finalRef.current)};r.onerror=()=>{setListening(false);setError('Input suara gagal. Pastikan izin mikrofon diberikan saat Anda menekan tombol mikrofon.')};r.onend=()=>{setListening(false);const value=finalRef.current.trim();if(value)void ask(value)};recognitionRef.current=r;setListening(true);r.start()};
 const close=()=>{recognitionRef.current?.stop();window.speechSynthesis?.cancel();setListening(false);setSpeaking(false);setOpen(false)};if(!role)return null;
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-20 right-4 z-[59] grid h-11 w-11 place-items-center rounded-full bg-white text-slate-950 shadow-xl ring-1 ring-slate-200 transition hover:scale-105 sm:bottom-20 sm:right-5" aria-label="Bicara dengan KerjaHarian AI" title="Bicara dengan KerjaHarian AI"><Mic className="h-4 w-4"/></button>{open&&<div className="fixed inset-x-3 bottom-3 z-[80] mx-auto max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl ring-1 ring-slate-200"><header className="flex items-center justify-between bg-slate-950 px-4 py-3 text-white"><div className="flex items-center gap-2"><Bot className="h-5 w-5"/><div><p className="text-sm font-extrabold">KerjaHarian AI</p><p className="text-[10px] text-slate-300">{role==='admin'?'Admin Operations':role==='employer'?'Employer Assistant':'Worker Assistant'}</p></div></div><div className="flex items-center gap-1"><button onClick={()=>{setVoiceOn(v=>!v);if(voiceOn)window.speechSynthesis?.cancel()}} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-white/10" aria-label={voiceOn?'Matikan suara':'Nyalakan suara'}>{voiceOn?<Volume2 className="h-4 w-4"/>:<VolumeX className="h-4 w-4"/>}</button><button onClick={close} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-white/10" aria-label="Tutup"><X className="h-4 w-4"/></button></div></header><div className="space-y-3 p-4"><p className="text-xs text-slate-500">Tekan mikrofon lalu bicara. AI akan menjawab dengan suara jika tersedia.</p>{answer&&<div className="rounded-xl bg-slate-50 p-3 text-sm leading-relaxed text-slate-700" aria-live="polite">{answer}</div>}{busy&&<div className="text-xs font-semibold text-slate-500">AI sedang memproses…</div>}{speaking&&<div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><Volume2 className="h-4 w-4 animate-pulse"/>AI sedang berbicara…</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</div>}<div className="flex items-center gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void ask()}} maxLength={1200} className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Atau ketik perintah…"/><button onClick={startListening} disabled={busy} className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl text-white ${listening?'bg-red-600':'bg-slate-950'}`} aria-label={listening?'Berhenti mendengar':'Mulai bicara'}>{listening?<MicOff className="h-5 w-5"/>:<Mic className="h-5 w-5"/>}</button><button onClick={()=>void ask()} disabled={busy||!text.trim()} className="rounded-xl bg-slate-200 px-3 py-3 text-xs font-bold disabled:opacity-40">Kirim</button></div>{!supported&&<p className="text-[10px] text-amber-700">Browser ini tidak mendukung Speech Recognition; gunakan input teks.</p>}</div></div>}</>;
}
