import { useState, useEffect, useCallback, type FormEvent } from 'react';
import { CheckCircle2, MapPin, Wallet, Info, Trash2, Send, Briefcase, Loader2, Clock3, PlusCircle } from 'lucide-react';
import { CATEGORIES, CATEGORY_MAP } from '@/lib/data';
import type { CategoryId } from '@/lib/types';
import { formatIDR, MIN_WAGE_DAILY, timeAgo } from '@/lib/format';
import { calculateOrderPrice } from '@/utils/pricingEngine';
import { useAuth } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import type { I18n } from '@/lib/i18n';

interface EmployerProps { onAuthClick:(mode:'signin'|'signup')=>void; initialCategory?:CategoryId|null; lang:'id'|'en'; i18n:I18n }
interface JobPrice { id:string; category_id:string; job_name:string; base_price:number; duration_minutes:number|null; overtime_rate_per_minute:number|null }
interface OrderItem { id:string; status:string; total_price:number; created_at:string; title?:string|null; job_prices?:{job_name:string}|null }
interface WalletState { available_balance:number; reserved_balance:number; total_balance:number }

declare global { interface Window { snap?:{pay:(token:string,options?:{onSuccess?:()=>void;onPending?:()=>void;onError?:()=>void;onClose?:()=>void})=>void} } }

function formatDuration(minutes:number|null,lang:'id'|'en'){if(!minutes||minutes<=0)return lang==='id'?'Durasi belum dikonfigurasi':'Duration not configured';const h=Math.floor(minutes/60),m=minutes%60;return lang==='en'?`${h?h+' hr'+(h!==1?'s':''):''}${h&&m?' ':''}${m?m+' min':''}`:`${h?h+' jam':''}${h&&m?' ':''}${m?m+' menit':''}`}
async function loadSnap(clientKey:string,environment:'sandbox'|'production'){if(window.snap)return;await new Promise<void>((resolve,reject)=>{const existing=document.querySelector('script[data-midtrans-snap]');if(existing){existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',()=>reject(new Error('Gagal memuat Midtrans Snap')),{once:true});return}const script=document.createElement('script');script.src=environment==='production'?'https://app.midtrans.com/snap/snap.js':'https://app.sandbox.midtrans.com/snap/snap.js';script.dataset.clientKey=clientKey;script.dataset.midtransSnap='true';script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error('Gagal memuat Midtrans Snap'));document.head.appendChild(script)})}

export function Employer({onAuthClick,initialCategory,lang,i18n:_i18n}:EmployerProps){
 const {user,profile,loading:authLoading}=useAuth();
 const [category,setCategory]=useState<CategoryId>(initialCategory??'logistik'); const [jobPrices,setJobPrices]=useState<JobPrice[]>([]); const [selectedJobPriceId,setSelectedJobPriceId]=useState<string|null>(null);
 const [title,setTitle]=useState(''); const [location,setLocation]=useState(''); const [wage,setWage]=useState(''); const [nightShift,setNightShift]=useState(false); const [needsTools,setNeedsTools]=useState(false);
 const [wallet,setWallet]=useState<WalletState|null>(null); const [walletBusy,setWalletBusy]=useState(false); const [topupAmount,setTopupAmount]=useState(''); const [topupOpen,setTopupOpen]=useState(false); const [topupError,setTopupError]=useState('');
 const [error,setError]=useState(''); const [success,setSuccess]=useState(false); const [submitting,setSubmitting]=useState(false); const [orders,setOrders]=useState<OrderItem[]>([]); const [loadingOrders,setLoadingOrders]=useState(false);
 const selectedJobPrice=jobPrices.find(j=>j.id===selectedJobPriceId)??null; const floorPrice=selectedJobPrice?.base_price??MIN_WAGE_DAILY; const wageNum=Math.max(0,parseInt(wage.replace(/[^0-9]/g,''),10)||0); const selectedCat=CATEGORY_MAP[category]; const pricing=calculateOrderPrice({wageAmount:wageNum,nightShift,needsTools}); const {nightShiftAdd,baseWage,platformFee,insurance,totalPrice}=pricing;
 const fetchWallet=useCallback(async()=>{if(!user||profile?.role!=='employer'){setWallet(null);return}const {data,error}=await supabase.rpc('get_employer_wallet');if(!error&&data?.[0])setWallet(data[0] as WalletState)},[user,profile?.role]);
 const fetchJobPrices=useCallback(async()=>{const dbCategory=category==='tukang'?'renovasi':category;const {data}=await supabase.from('job_prices').select('id,category_id,job_name,base_price,duration_minutes,overtime_rate_per_minute').eq('category_id',dbCategory).eq('is_active',true).order('job_name',{ascending:true});if(data){setJobPrices(data as JobPrice[]);setSelectedJobPriceId(null);setWage('')}},[category]);
 const fetchOrders=useCallback(async()=>{if(!user)return;setLoadingOrders(true);const {data}=await supabase.from('orders').select('id,status,total_price,created_at,title,job_prices(job_name)').eq('employer_id',user.id).order('created_at',{ascending:false}).limit(10);if(data)setOrders(data as unknown as OrderItem[]);setLoadingOrders(false)},[user]);
 useEffect(()=>{void fetchJobPrices()},[fetchJobPrices]); useEffect(()=>{void fetchOrders();void fetchWallet()},[fetchOrders,fetchWallet]); useEffect(()=>{if(initialCategory)setCategory(initialCategory)},[initialCategory]); useEffect(()=>{if(selectedJobPrice)setWage(String(selectedJobPrice.base_price))},[selectedJobPrice]);
 const canOrder=Boolean(user&&profile?.role==='employer'&&profile.kyc_verified&&selectedJobPrice&&location.trim()&&wageNum>=floorPrice&&wallet&&wallet.available_balance>=totalPrice&&!submitting);
 const topUp=async()=>{setTopupError('');const amount=Number(topupAmount.replace(/[^0-9]/g,''));if(!Number.isInteger(amount)||amount<10000||amount>50000000){setTopupError(lang==='id'?'Top-up minimal Rp10.000 dan maksimal Rp50.000.000.':'Top-up must be Rp10,000 to Rp50,000,000.');return}setWalletBusy(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Sesi login tidak ditemukan');const response=await fetch('/api/midtrans/create-wallet-topup',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({amount})});const result=await response.json().catch(()=>({}));if(!response.ok||!result.token||!result.client_key)throw new Error(result.error||'Gagal membuat transaksi top-up');const env=result.environment==='production'?'production':'sandbox';await loadSnap(result.client_key,env);if(!window.snap)throw new Error('Midtrans Snap belum siap');window.snap.pay(result.token,{onSuccess:()=>{void (async()=>{for(let i=0;i<30;i++){const {data}=await supabase.from('employer_wallet_topups').select('status').eq('id',result.topup_id).single();if(data?.status==='settled'){await fetchWallet();setTopupOpen(false);setTopupAmount('');setWalletBusy(false);return}if(['cancelled','refunded','review'].includes(String(data?.status))){throw new Error('Top-up belum dapat dikreditkan. Silakan cek status pembayaran.')}await new Promise(r=>setTimeout(r,1000))}throw new Error('Settlement belum terkonfirmasi. Saldo belum ditambahkan.')})().catch(e=>{setTopupError(e instanceof Error?e.message:'Top-up belum terkonfirmasi');setWalletBusy(false)})},onPending:()=>{setTopupError(lang==='id'?'Pembayaran masih menunggu settlement Midtrans. Saldo belum ditambahkan.':'Payment is pending Midtrans settlement. Balance has not been added.');setWalletBusy(false)},onError:()=>{setTopupError(lang==='id'?'Pembayaran gagal. Saldo tidak berubah.':'Payment failed. Balance unchanged.');setWalletBusy(false)},onClose:()=>setWalletBusy(false)})}catch(e){setTopupError(e instanceof Error?e.message:'Gagal top-up');setWalletBusy(false)}};
 const handleSubmit=async(e:FormEvent)=>{e.preventDefault();setError('');setSuccess(false);if(!user){onAuthClick('signup');return}if(!profile?.kyc_verified){setError(lang==='id'?'Verifikasi KTP + selfie Employer diperlukan sebelum memesan.':'Employer KTP + selfie verification is required before ordering.');return}if(!selectedJobPrice){setError(lang==='id'?'Pilih jenis pekerjaan terlebih dahulu.':'Please select job type first.');return}if(!selectedJobPrice.duration_minutes){setError(lang==='id'?'Durasi pekerjaan belum dikonfigurasi.':'Job duration is not configured.');return}if(!location.trim()){setError(lang==='id'?'Lokasi pengerjaan wajib diisi.':'Job location is required.');return}if(wageNum<floorPrice){setError(lang==='id'?`Upah minimum ${formatIDR(floorPrice)}.`:`Minimum wage ${formatIDR(floorPrice)}.`);return}if(!wallet||wallet.available_balance<totalPrice){setError(lang==='id'?`Saldo tidak cukup. Wajib top-up ${formatIDR(Math.max(0,totalPrice-(wallet?.available_balance??0)))} sebelum Order.`:`Insufficient balance. Top up ${formatIDR(Math.max(0,totalPrice-(wallet?.available_balance??0)))} before ordering.`);setTopupOpen(true);return}setSubmitting(true);const {data,error:rpcError}=await supabase.rpc('create_prepaid_order',{p_job_price_id:selectedJobPrice.id,p_title:title,p_location:location,p_wage:wageNum,p_night_shift:nightShift,p_needs_tools:needsTools,p_hours:Math.ceil(selectedJobPrice.duration_minutes/60)});if(rpcError||!data?.[0]){setError(rpcError?.message||'Order gagal dibuat');setSubmitting(false);return}const orderId=data[0].order_id;const {data:orderData}=await supabase.from('orders').select('id,status,total_price,created_at,title,job_prices(job_name)').eq('id',orderId).single();if(orderData)setOrders(prev=>[orderData as OrderItem,...prev]);try{const controller=new AbortController();const timeoutId=setTimeout(()=>controller.abort(),5000);const geoRes=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(location.trim())}&countrycodes=id&limit=1`,{signal:controller.signal});clearTimeout(timeoutId);if(geoRes.ok){const geoData=await geoRes.json();if(geoData?.length){await supabase.from('order_locations').insert([{order_id:orderId,lat:parseFloat(geoData[0].lat),lng:parseFloat(geoData[0].lon)}])}}}catch(err){console.warn('Geocoding failed:',err)}setTitle('');setLocation('');setWage('');setSuccess(true);setSubmitting(false);await fetchWallet();setTimeout(()=>setSuccess(false),5000)};
 const cancelOrder=async(id:string)=>{const {error:e}=await supabase.from('orders').update({status:'cancelled'}).eq('id',id).eq('employer_id',user?.id??'');if(!e){setOrders(prev=>prev.map(o=>o.id===id?{...o,status:'cancelled'}:o));await fetchWallet()}};
 return <div className="bg-slate-50 pb-20 pt-8"><div className="container-app"><div className="mb-8"><div className="inline-flex items-center gap-2 rounded-full bg-primary-50 px-3 py-1 text-xs font-semibold text-primary-700"><Briefcase className="h-3.5 w-3.5"/>{lang==='id'?'Pemberi Kerja':'Employer'}</div><h1 className="mt-3 font-display text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">{lang==='id'?'Pesan Tenaga Kerja':'Hire Workers'}</h1><p className="mt-2 max-w-xl text-slate-500">{lang==='id'?'Lihat total final terlebih dahulu. Saldo wajib cukup sebelum Order.':'See the final total first. Balance must be sufficient before ordering.'}</p></div>
 <div className="mb-6 grid gap-4 md:grid-cols-2"><div className="card flex items-center justify-between p-5"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{lang==='id'?'Saldo tersedia':'Available balance'}</p><p className="mt-1 text-2xl font-extrabold text-slate-900">{formatIDR(wallet?.available_balance??0)}</p><p className="mt-1 text-xs text-slate-500">{lang==='id'?`Dana terkunci: ${formatIDR(wallet?.reserved_balance??0)}`:`Reserved: ${formatIDR(wallet?.reserved_balance??0)}`}</p></div><button type="button" onClick={()=>{setTopupError('');setTopupOpen(true)}} className="btn-primary flex items-center gap-2"><PlusCircle className="h-4 w-4"/>{lang==='id'?'Top Up':'Top Up'}</button></div>{!profile?.kyc_verified&&user&&<div className="card border-amber-200 bg-amber-50 p-5 text-sm font-semibold text-amber-800">{lang==='id'?'KTP + selfie Employer harus disetujui admin sebelum Order.':'Employer KTP + selfie must be approved before ordering.'}</div>}</div>
 <div className="grid gap-6 lg:grid-cols-5"><div className="lg:col-span-3"><form onSubmit={handleSubmit} className="card p-6 sm:p-8"><h2 className="font-display text-lg font-bold text-slate-900">{lang==='id'?'1. Pilih Kategori':'1. Select Category'}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{CATEGORIES.map(cat=><button key={cat.id} type="button" onClick={()=>setCategory(cat.id)} className={`flex items-center gap-3 rounded-lg border-2 px-4 py-3 ${category===cat.id?'border-primary-500 bg-primary-50':'border-slate-200 bg-white'}`}><cat.icon className="h-5 w-5"/><span className="text-sm font-semibold">{cat.label}</span></button>)}</div>
 <h2 className="mt-8 font-display text-lg font-bold text-slate-900">{lang==='id'?'2. Detail Pekerjaan':'2. Job Details'}</h2><div className="mt-4 space-y-4"><div><label className="label">{lang==='id'?'Jenis Pekerjaan':'Job Type'}</label><select value={selectedJobPriceId||''} onChange={e=>setSelectedJobPriceId(e.target.value||null)} className="input"><option value="">{lang==='id'?'Pilih jenis...':'Select type...'}</option>{jobPrices.map(j=><option key={j.id} value={j.id}>{j.job_name}</option>)}</select></div>{selectedJobPrice&&<div className="rounded-xl border border-primary-100 bg-primary-50/70 p-4"><div className="flex gap-3"><Clock3 className="h-5 w-5 text-primary-600"/><div><p className="text-xs font-bold uppercase text-primary-700">{lang==='id'?'Ketentuan Deal':'Deal Terms'}</p><p className="mt-1 font-bold">{formatDuration(selectedJobPrice.duration_minutes,lang)}</p><p className="mt-2 text-xs text-slate-600">{lang==='id'?'Harga final dihitung server dari katalog harga dan pilihan shift malam.':'Final price is calculated server-side from the price catalog and night-shift choice.'}</p></div></div></div>}
 <div><label className="label">{lang==='id'?'Detail (opsional)':'Details (optional)'}</label><textarea value={title} onChange={e=>setTitle(e.target.value)} rows={3} placeholder={selectedCat?.examples[0]||''} className="input"/></div><div><label className="label">{lang==='id'?'Lokasi Pengerjaan':'Job Location'}</label><div className="relative"><MapPin className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder={lang==='id'?'Contoh: Jl. Sudirman, Jakarta':'e.g. Jl. Sudirman, Jakarta'} className="input pl-10"/></div></div><div className="flex gap-2"><button type="button" onClick={()=>setNightShift(v=>!v)} className={`flex-1 rounded-lg border-2 px-4 py-2.5 text-sm font-semibold ${nightShift?'border-primary-500 bg-primary-50':'border-slate-200 bg-white'}`}>🌙 {lang==='id'?'Shift Malam +20%':'Night Shift +20%'}</button><button type="button" onClick={()=>setNeedsTools(v=>!v)} className={`flex-1 rounded-lg border-2 px-4 py-2.5 text-sm font-semibold ${needsTools?'border-primary-500 bg-primary-50':'border-slate-200 bg-white'}`}>🔧 {lang==='id'?'Saran Bawa Alat':'Suggest Tools'}</button></div><p className="text-xs text-slate-500">{lang==='id'?'Saran alat hanya informasi dan tidak menambah biaya.':'Tools are informational only and add no charge.'}</p><div><label className="label">{lang==='id'?`Upah (min ${formatIDR(floorPrice)})`:`Wage (min ${formatIDR(floorPrice)})`}</label><div className="relative"><Wallet className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={wage?`Rp ${parseInt(wage.replace(/[^0-9]/g,''),10).toLocaleString('id-ID')}:''`} onChange={e=>setWage(e.target.value.replace(/[^0-9]/g,''))} placeholder={`Rp ${formatIDR(floorPrice)}`} className="input pl-10"/></div></div></div>
 <h2 className="mt-8 font-display text-lg font-bold text-slate-900">{lang==='id'?'3. Total Final':'3. Final Total'}</h2><div className="mt-4 rounded-xl bg-slate-50 p-5 ring-1 ring-slate-200"><SummaryRow label={lang==='id'?'Durasi Deal':'Deal Duration'} value={formatDuration(selectedJobPrice?.duration_minutes??null,lang)}/><SummaryRow label={lang==='id'?'Upah Pokok':'Base Wage'} value={formatIDR(baseWage)}/>{nightShift&&<SummaryRow label={lang==='id'?'Shift Malam':'Night Shift'} value={formatIDR(nightShiftAdd)}/>}<SummaryRow label={lang==='id'?'Platform + Asuransi':'Platform + Insurance'} value={formatIDR(platformFee+insurance.microInsurance)} muted/><div className="my-3 border-t border-dashed border-slate-300"/><div className="flex justify-between"><span className="font-bold">Total</span><span className="text-xl font-extrabold text-primary-700">{formatIDR(totalPrice)}</span></div><div className={`mt-3 rounded-lg p-3 text-xs font-bold ${wallet&&wallet.available_balance>=totalPrice?'bg-success-50 text-success-700':'bg-amber-50 text-amber-800'}`}>{wallet&&wallet.available_balance>=totalPrice?(lang==='id'?'Saldo cukup — Order dapat dilakukan.':'Balance sufficient — Order is available.'):(lang==='id'?`Wajib top-up ${formatIDR(Math.max(0,totalPrice-(wallet?.available_balance??0)))} sebelum Order.`:`Top up ${formatIDR(Math.max(0,totalPrice-(wallet?.available_balance??0)))} before ordering.`)}</div></div>{error&&<div className="mt-4 flex gap-2 rounded-lg bg-error-50 px-4 py-3 text-sm font-semibold text-error-700"><Info className="h-4 w-4"/>{error}</div>}{success&&<div className="mt-4 flex gap-2 rounded-lg bg-success-50 px-4 py-3 text-sm font-semibold text-success-700"><CheckCircle2 className="h-4 w-4"/>{lang==='id'?'Pesanan berhasil dibuat dan dananya dikunci.':'Order created and funds reserved.'}</div>}<button type="submit" disabled={!canOrder||authLoading} className="btn-primary mt-6 flex w-full items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed">{submitting?<Loader2 className="h-5 w-5 animate-spin"/>:<Send className="h-5 w-5"/>}{submitting?(lang==='id'?'Membuat Order...':'Creating Order...'):(lang==='id'?'Order':'Order')}</button></form></div>
 <div className="lg:col-span-2"><div className="card p-6 sm:p-8"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold">{lang==='id'?'Pesanan Saya':'My Orders'}</h2>{loadingOrders&&<Loader2 className="h-4 w-4 animate-spin"/>}</div><div className="mt-4 space-y-3">{!user?<p className="text-sm text-slate-500">{lang==='id'?'Login untuk melihat pesanan.':'Sign in to view orders.'}</p>:orders.length===0?<p className="text-sm text-slate-500">{lang==='id'?'Belum ada pesanan.':'No orders yet.'}</p>:orders.map(order=><div key={order.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{order.title||order.job_prices?.job_name||'Pekerjaan'}</p><p className="mt-1 text-xs text-slate-500">{timeAgo(order.created_at,lang)}</p></div>{['open','assigned'].includes(order.status)&&<button type="button" onClick={()=>cancelOrder(order.id)} className="rounded-lg p-2 text-slate-400 hover:bg-error-50 hover:text-error-600" aria-label={lang==='id'?'Batalkan pesanan':'Cancel order'}><Trash2 className="h-4 w-4"/></button>}</div><div className="mt-3 flex justify-between text-sm"><span className="rounded-full bg-slate-100 px-2.5 py-1 font-medium">{order.status}</span><span className="font-bold text-primary-700">{formatIDR(order.total_price)}</span></div></div>)}</div></div></div></div></div>
 {topupOpen&&<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4" onClick={()=>!walletBusy&&setTopupOpen(false)}><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl" onClick={e=>e.stopPropagation()}><h2 className="text-lg font-extrabold">{lang==='id'?'Top Up Saldo Employer':'Top Up Employer Balance'}</h2><p className="mt-1 text-xs text-slate-500">{lang==='id'?'Saldo hanya bertambah setelah settlement Midtrans terkonfirmasi.':'Balance increases only after confirmed Midtrans settlement.'}</p>{topupError&&<div className="mt-4 rounded-lg bg-error-50 p-3 text-xs font-semibold text-error-700">{topupError}</div>}<label className="label mt-4">{lang==='id'?'Nominal':'Amount'}</label><input className="input" inputMode="numeric" value={topupAmount} onChange={e=>setTopupAmount(e.target.value)} placeholder="500000"/><button disabled={walletBusy} onClick={()=>void topUp()} className="btn-primary mt-4 flex w-full justify-center gap-2">{walletBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<Wallet className="h-4 w-4"/>}{walletBusy?(lang==='id'?'Memproses...':'Processing...'):(lang==='id'?'Bayar via Midtrans':'Pay via Midtrans')}</button><button disabled={walletBusy} onClick={()=>setTopupOpen(false)} className="btn-ghost mt-2 w-full">{lang==='id'?'Tutup':'Close'}</button></div></div>}
 </div>
}
function SummaryRow({label,value,muted=false}:{label:string;value:string;muted?:boolean}){return <div className="flex items-center justify-between gap-4 py-1.5 text-sm"><span className={muted?'text-slate-500':'text-slate-700'}>{label}</span><span className={muted?'font-medium text-slate-600':'font-semibold text-slate-900'}>{value}</span></div>}
