import { HardHat, MapPin, Phone, Shield, MessageCircle } from 'lucide-react';
import { Logo } from './Logo';
import type { View, CategoryId } from '@/lib/types';

interface FooterProps { onNavigate: (view: View, category?: CategoryId) => void; }
const LinkItem = ({ href, children, onNavigate, view }: { href: string; children: React.ReactNode; onNavigate: (view: View) => void; view: View }) => <a href={href} onClick={(e) => { e.preventDefault(); onNavigate(view); }} className="transition hover:text-white">{children}</a>;

export function Footer({ onNavigate }: FooterProps) {
  return <footer className="bg-primary-950 text-slate-300"><div className="container-app py-14"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4">
    <div><div className="rounded-xl bg-white/5 p-3 ring-1 ring-white/10"><Logo className="[&_span]:text-white [&_.text-slate-400]:text-slate-400" /></div><p className="mt-4 max-w-xs text-sm leading-relaxed text-slate-400">Platform on-demand yang menghubungkan pemberi kerja dengan tenaga kerja harian di Indonesia.</p><p className="mt-4 text-xs font-semibold text-slate-500">KerjaHarian</p></div>
    <div><h4 className="text-sm font-bold uppercase tracking-wider text-white">Layanan</h4><ul className="mt-4 space-y-2.5 text-sm"><li><LinkItem href="/cari-pekerja" onNavigate={onNavigate} view="employer">Pesan Tenaga Kerja</LinkItem></li><li><LinkItem href="/cari-kerja" onNavigate={onNavigate} view="worker">Jadi Mitra Pekerja</LinkItem></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','logistik')}} className="text-slate-500 transition hover:text-white">Logistik & Pindahan</a></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','tukang')}} className="text-slate-500 transition hover:text-white">Tukang & Renovasi</a></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','kebersihan')}} className="text-slate-500 transition hover:text-white">Jasa Kebersihan Rumah</a></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','serabutan')}} className="text-slate-500 transition hover:text-white">Tenaga Serabutan Profesional</a></li></ul></div>
    <div><h4 className="text-sm font-bold uppercase tracking-wider text-white">Perusahaan & Legal</h4><ul className="mt-4 space-y-2.5 text-sm"><li><LinkItem href="/" onNavigate={onNavigate} view="landing">Tentang Kami</LinkItem></li><li><LinkItem href="/privacy" onNavigate={onNavigate} view="privacy">Kebijakan Privasi</LinkItem></li><li><LinkItem href="/terms" onNavigate={onNavigate} view="terms">Syarat & Ketentuan</LinkItem></li><li><LinkItem href="/help" onNavigate={onNavigate} view="help">Pusat Bantuan</LinkItem></li></ul></div>
    <div><h4 className="text-sm font-bold uppercase tracking-wider text-white">Kontak Resmi CS</h4><ul className="mt-4 space-y-3 text-sm"><li className="flex items-center gap-2.5"><MapPin className="h-4 w-4 text-primary-300 flex-shrink-0"/><span>Jakarta, Indonesia</span></li><li className="flex items-center gap-2.5"><Phone className="h-4 w-4 text-primary-300 flex-shrink-0"/><span>+62 882-8976-7019</span></li><li><a href="https://wa.me/6288289767019" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white text-xs px-3 py-2 rounded-lg font-semibold transition shadow-sm mt-1"><MessageCircle className="h-3.5 w-3.5"/>Chat WhatsApp CS</a></li><li className="flex items-center gap-2.5 pt-1"><Shield className="h-4 w-4 text-primary-300 flex-shrink-0"/><span className="text-xs">Layanan KerjaHarian</span></li></ul></div>
  </div><div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-white/10 pt-6 text-xs text-slate-500 sm:flex-row"><p>© 2026 KerjaHarian. Semua hak dilindungi.</p><div className="flex items-center gap-1.5"><HardHat className="h-3.5 w-3.5 text-primary-400"/><span>Solusi Cepat Tenaga Kerja Harian</span></div></div></div></footer>;
}
