import { HardHat, MapPin, Phone, Shield, MessageCircle } from 'lucide-react';
import { Logo } from './Logo';
import type { View, CategoryId } from '@/lib/types';

interface FooterProps { onNavigate: (view: View, category?: CategoryId) => void; lang?: 'id' | 'en'; }
const LinkItem = ({ href, children, onNavigate, view }: { href: string; children: React.ReactNode; onNavigate: (view: View) => void; view: View }) => <a href={href} onClick={(e) => { e.preventDefault(); onNavigate(view); }} className="transition hover:text-white">{children}</a>;

export function Footer({ onNavigate, lang }: FooterProps) {
  const currentLang = lang ?? ((typeof window !== 'undefined' && localStorage.getItem('kerjaharian_lang') === 'en') ? 'en' : 'id');
  const id = currentLang === 'id';
  const t = id ? {
    description: 'Platform on-demand yang menghubungkan pemberi kerja dengan tenaga kerja harian di Indonesia.', services: 'Layanan', hire: 'Pesan Tenaga Kerja', worker: 'Jadi Mitra Pekerja', logistics: 'Logistik & Pindahan', renovation: 'Tukang & Renovasi', cleaning: 'Jasa Kebersihan Rumah', general: 'Tenaga Serabutan Profesional', legal: 'Perusahaan & Legal', about: 'Tentang Kami', privacy: 'Kebijakan Privasi', terms: 'Syarat & Ketentuan', help: 'Pusat Bantuan', contact: 'Kontak Resmi CS', chat: 'Chat WhatsApp CS', service: 'Layanan KerjaHarian', rights: 'Semua hak dilindungi.', tagline: 'Solusi Cepat Tenaga Kerja Harian'
  } : {
    description: 'An on-demand marketplace connecting employers with daily workers across Indonesia.', services: 'Services', hire: 'Hire Daily Workers', worker: 'Join as a Worker', logistics: 'Logistics & Moving', renovation: 'Repairs & Renovation', cleaning: 'Home Cleaning Services', general: 'General Labor', legal: 'Company & Legal', about: 'About Us', privacy: 'Privacy Policy', terms: 'Terms & Conditions', help: 'Help Center', contact: 'Official Customer Support', chat: 'Chat with WhatsApp Support', service: 'KerjaHarian Service', rights: 'All rights reserved.', tagline: 'Fast Daily Workforce Solutions'
  };
  return <footer className="bg-primary-950 text-slate-300"><div className="container-app py-14"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4">
    <div><div className="rounded-xl bg-white/5 p-3 ring-1 ring-white/10"><Logo className="[&_span]:text-white [&_.text-slate-400]:text-slate-400" /></div><p className="mt-4 max-w-xs text-sm leading-relaxed text-slate-400">{t.description}</p><p className="mt-4 text-xs font-semibold text-slate-500">KerjaHarian</p></div>
    <div><h4 className="text-sm font-bold uppercase tracking-wider text-white">{t.services}</h4><ul className="mt-4 space-y-2.5 text-sm"><li><LinkItem href="/cari-pekerja" onNavigate={onNavigate} view="employer">{t.hire}</LinkItem></li><li><LinkItem href="/cari-kerja" onNavigate={onNavigate} view="worker">{t.worker}</LinkItem></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','logistik')}} className="text-slate-500 transition hover:text-white">{t.logistics}</a></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','tukang')}} className="text-slate-500 transition hover:text-white">{t.renovation}</a></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','kebersihan')}} className="text-slate-500 transition hover:text-white">{t.cleaning}</a></li><li><a href="/cari-pekerja" onClick={(e)=>{e.preventDefault();onNavigate('employer','serabutan')}} className="text-slate-500 transition hover:text-white">{t.general}</a></li></ul></div>
    <div><h4 className="text-sm font-bold uppercase tracking-wider text-white">{t.legal}</h4><ul className="mt-4 space-y-2.5 text-sm"><li><LinkItem href="/" onNavigate={onNavigate} view="landing">{t.about}</LinkItem></li><li><LinkItem href="/privacy" onNavigate={onNavigate} view="privacy">{t.privacy}</LinkItem></li><li><LinkItem href="/terms" onNavigate={onNavigate} view="terms">{t.terms}</LinkItem></li><li><LinkItem href="/help" onNavigate={onNavigate} view="help">{t.help}</LinkItem></li></ul></div>
    <div><h4 className="text-sm font-bold uppercase tracking-wider text-white">{t.contact}</h4><ul className="mt-4 space-y-3 text-sm"><li className="flex items-center gap-2.5"><MapPin className="h-4 w-4 text-primary-300 flex-shrink-0"/><span>Jakarta, Indonesia</span></li><li className="flex items-center gap-2.5"><Phone className="h-4 w-4 text-primary-300 flex-shrink-0"/><span>+62 882-8976-7019</span></li><li><a href="https://wa.me/6288289767019" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white text-xs px-3 py-2 rounded-lg font-semibold transition shadow-sm mt-1"><MessageCircle className="h-3.5 w-3.5"/>{t.chat}</a></li><li className="flex items-center gap-2.5 pt-1"><Shield className="h-4 w-4 text-primary-300 flex-shrink-0"/><span className="text-xs">{t.service}</span></li></ul></div>
  </div><div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-white/10 pt-6 text-xs text-slate-500 sm:flex-row"><p>© 2026 KerjaHarian. {t.rights}</p><div className="flex items-center gap-1.5"><HardHat className="h-3.5 w-3.5 text-primary-400"/><span>{t.tagline}</span></div></div></div></footer>;
}
