import { useState } from 'react';
import { ArrowRight, CheckCircle2, Clock3, Menu, MessageCircle, ShieldCheck, X, Zap } from 'lucide-react';
import { Logo } from './Logo';
import type { View } from '@/lib/types';

interface LandingDarkProps { onNavigate: (view: View) => void; lang: 'id' | 'en'; }

const services = [
  ['Angkut & Logistik', 'Tenaga untuk angkut, bongkar muat, dan kebutuhan barang.'],
  ['Bersih-bersih', 'Bantuan untuk rumah, kantor, toko, dan area usaha.'],
  ['Pindahan', 'Tenaga tambahan saat memindahkan barang dan perlengkapan.'],
  ['Potong Rumput', 'Bantuan untuk halaman, kebun, dan area luar.'],
];

const faqs = [
  ['Bagaimana cara mencari pekerja?', 'Pilih kebutuhan pekerjaan, lihat pilihan yang tersedia, lalu lanjutkan pemesanan.'],
  ['Bagaimana cara mencari pekerjaan?', 'Daftar sebagai Pekerja dan lihat pekerjaan yang tersedia di area Anda.'],
  ['Bagaimana cara mengetahui harga?', 'Harga pekerjaan ditampilkan sebelum Anda melanjutkan pemesanan.'],
  ['Bagaimana cara pembayaran?', 'Pembayaran dilakukan melalui metode pembayaran yang tersedia di KerjaHarian.'],
  ['Kapan pekerjaan dimulai?', 'Pekerjaan dimulai mengikuti status pekerjaan dan proses check-in di aplikasi.'],
  ['Bagaimana jika ada masalah?', 'Gunakan Pusat Bantuan KerjaHarian untuk mendapatkan bantuan.'],
];

const socials = ['Facebook', 'Instagram', 'TikTok', 'YouTube', 'LinkedIn', 'X', 'WhatsApp'];

export function LandingDark({ onNavigate, lang }: LandingDarkProps) {
  const id = lang === 'id';
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const go = (view: View) => { setMenuOpen(false); onNavigate(view); };
  const scrollTo = (target: string) => { setMenuOpen(false); document.getElementById(target)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };

  return (
    <main className="min-h-screen bg-[#050505] text-white">
      <header className="sticky top-0 z-[80] border-b border-white/10 bg-[#050505]/90 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <button type="button" onClick={() => scrollTo('top')} className="flex items-center gap-2" aria-label="KerjaHarian"><Logo className="[&_span]:text-white [&_.text-slate-400]:text-white/50" /></button>
          <div className="flex items-center gap-2">
            <button type="button" onClick={() => go('employer')} className="hidden rounded-lg bg-orange-500 px-4 py-2 text-xs font-black text-white sm:block">{id ? 'Butuh Pekerja' : 'Hire Workers'}</button>
            <button type="button" onClick={() => setMenuOpen(v => !v)} aria-label="Menu" className="grid h-10 w-10 place-items-center rounded-lg border border-white/15 text-white">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button>
          </div>
        </div>
        {menuOpen && <div className="border-t border-white/10 bg-[#080808]"><nav className="mx-auto flex max-w-7xl flex-col px-4 py-3 sm:px-6 lg:px-8">
          <button type="button" onClick={() => scrollTo('services')} className="border-b border-white/10 px-1 py-3 text-left text-sm font-semibold text-white/75">Layanan</button>
          <button type="button" onClick={() => scrollTo('how')} className="border-b border-white/10 px-1 py-3 text-left text-sm font-semibold text-white/75">Cara Kerja</button>
          <button type="button" onClick={() => go('employer')} className="border-b border-white/10 px-1 py-3 text-left text-sm font-semibold text-white/75">Untuk Pemberi Kerja</button>
          <button type="button" onClick={() => go('worker')} className="border-b border-white/10 px-1 py-3 text-left text-sm font-semibold text-white/75">Untuk Pekerja</button>
          <button type="button" onClick={() => go('help')} className="border-b border-white/10 px-1 py-3 text-left text-sm font-semibold text-white/75">Bantuan</button>
          <button type="button" onClick={() => go('terms')} className="border-b border-white/10 px-1 py-3 text-left text-sm font-semibold text-white/75">Syarat & Ketentuan</button>
          <button type="button" onClick={() => go('privacy')} className="px-1 py-3 text-left text-sm font-semibold text-white/75">Kebijakan Privasi</button>
        </nav></div>}
      </header>

      <section id="top" className="scroll-mt-20 border-b border-white/10">
        <div className="mx-auto grid max-w-7xl items-center gap-8 px-4 py-10 sm:px-6 sm:py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20">
          <div><p className="text-xs font-black uppercase tracking-[.22em] text-orange-500">KERJAHARIAN</p><h1 className="mt-5 text-5xl font-black leading-[.94] tracking-[-.05em] sm:text-7xl">Kerja Nyata,<br /><span className="text-orange-500">Untuk Kebutuhan Nyata.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/60 sm:text-lg">KerjaHarian mempertemukan orang yang membutuhkan tenaga kerja dengan orang yang siap bekerja.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => go('employer')} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-orange-500 px-7 py-3.5 text-sm font-black">BUTUH PEKERJA <ArrowRight className="h-4 w-4" /></button><button type="button" onClick={() => go('worker')} className="flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-7 py-3.5 text-sm font-black">CARI KERJA</button></div></div>
          <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-[#111]"><img src="https://images.pexels.com/photos/37599792/pexels-photo-37599792.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Pekerja menurunkan dan menata barang di Jakarta" className="h-[360px] w-full object-cover sm:h-[500px]" /></div>
        </div>
      </section>

      <section className="border-b border-white/10 bg-[#090909]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-8 md:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-500">Untuk kebutuhan sehari-hari</p><h2 className="mt-3 max-w-xl text-3xl font-black tracking-tight sm:text-5xl">Saat butuh tenaga, Anda butuh orang yang siap bekerja.</h2></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#111] p-5"><Zap className="h-5 w-5 text-orange-500"/><p className="mt-4 font-black">Cepat</p><p className="mt-2 text-sm leading-6 text-white/50">Temukan kebutuhan tenaga kerja tanpa proses yang berbelit.</p></div><div className="rounded-2xl border border-white/10 bg-[#111] p-5"><Clock3 className="h-5 w-5 text-orange-500"/><p className="mt-4 font-black">Harian</p><p className="mt-2 text-sm leading-6 text-white/50">Pekerjaan fisik untuk kebutuhan hari ini dan seterusnya.</p></div></div></div></div></section>

      <section id="services" className="scroll-mt-20 border-b border-white/10"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-500">Layanan</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Pilih kebutuhan Anda.</h2></div><button type="button" onClick={() => go('employer')} className="flex items-center gap-2 text-sm font-black text-orange-500">Lihat layanan <ArrowRight className="h-4 w-4" /></button></div><div className="mt-8 flex flex-wrap gap-3">{services.map(([title, text]) => <button type="button" key={title} onClick={() => go('employer')} className="group min-w-[210px] flex-1 rounded-2xl border border-white/10 bg-[#0b0b0b] p-5 text-left transition hover:border-orange-500/40"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{title}</h3><ArrowRight className="h-4 w-4 shrink-0 text-orange-500 transition group-hover:translate-x-1" /></div><p className="mt-2 text-sm leading-6 text-white/45">{text}</p></button>)}</div></div></section>

      <section id="how" className="scroll-mt-20 border-b border-white/10 bg-[#090909]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-500">Cara Kerja</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Satu alur. Dua kebutuhan.</h2><div className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-orange-500 p-7 text-black"><p className="text-xs font-black uppercase tracking-wider">Pemberi Kerja</p><h3 className="mt-3 text-2xl font-black">Butuh tenaga?</h3><p className="mt-5 text-sm font-bold leading-7">Pilih kebutuhan → lihat harga → pesan → pekerja menerima → pekerjaan berjalan → selesai.</p></div><div className="rounded-3xl border border-white/10 bg-[#111] p-7"><p className="text-xs font-black uppercase tracking-wider text-orange-500">Pekerja</p><h3 className="mt-3 text-2xl font-black">Siap bekerja?</h3><p className="mt-5 text-sm font-bold leading-7 text-white/70">Lihat pekerjaan → pilih → terima → check-in → kerjakan → selesai.</p></div></div></div></section>

      <section className="border-b border-white/10"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-4 lg:grid-cols-2"><button type="button" onClick={() => go('employer')} className="group rounded-3xl border border-white/10 bg-[#111] p-7 text-left sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-500">Pemberi Kerja</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Butuh orang untuk pekerjaan Anda?</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/50">Daftar, lengkapi verifikasi, lalu gunakan KerjaHarian untuk kebutuhan tenaga kerja harian.</p><span className="mt-7 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-black">Bergabung <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></button><button type="button" onClick={() => go('worker')} className="group rounded-3xl border border-white/10 bg-[#111] p-7 text-left sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-500">Pekerja</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Siap bekerja hari ini?</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/50">Daftar, selesaikan verifikasi, dan temukan pekerjaan yang tersedia untuk Anda.</p><span className="mt-7 inline-flex items-center gap-2 rounded-xl border border-white/15 px-5 py-3 text-sm font-black">Cari kerja <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></button></div></div></section>

      <section className="border-b border-white/10 bg-[#090909]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-500">Aman dan terstruktur</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Yang penting terlihat jelas.</h2></div><p className="max-w-md text-sm leading-6 text-white/50">Identitas, harga, status pekerjaan, pembayaran, dan penyelesaian pekerjaan mengikuti sistem KerjaHarian.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-[#111] p-5"><ShieldCheck className="h-5 w-5 text-orange-500"/><p className="mt-4 font-black">Identitas</p><p className="mt-2 text-sm text-white/45">Verifikasi sesuai peran.</p></div><div className="rounded-2xl border border-white/10 bg-[#111] p-5"><CheckCircle2 className="h-5 w-5 text-orange-500"/><p className="mt-4 font-black">Harga</p><p className="mt-2 text-sm text-white/45">Harga pekerjaan ditampilkan jelas.</p></div><div className="rounded-2xl border border-white/10 bg-[#111] p-5"><Clock3 className="h-5 w-5 text-orange-500"/><p className="mt-4 font-black">Status</p><p className="mt-2 text-sm text-white/45">Tahapan pekerjaan dapat diikuti.</p></div><div className="rounded-2xl border border-white/10 bg-[#111] p-5"><MessageCircle className="h-5 w-5 text-orange-500"/><p className="mt-4 font-black">Bantuan</p><p className="mt-2 text-sm text-white/45">Ada jalur bantuan ketika dibutuhkan.</p></div></div></div></section>

      <section id="faq" className="scroll-mt-20 border-b border-white/10"><div className="mx-auto max-w-4xl px-4 py-14 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-500">Bantuan</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Pertanyaan yang sering ditanyakan.</h2><div className="mt-8 divide-y divide-white/10 rounded-2xl border border-white/10 bg-[#0b0b0b]">{faqs.map(([question, answer], index) => <div key={question}><button type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-5 px-5 py-5 text-left text-sm font-black sm:px-6"><span>{question}</span><span className="text-xl text-orange-500">{openFaq === index ? '−' : '+'}</span></button>{openFaq === index && <p className="px-5 pb-5 text-sm leading-6 text-white/50 sm:px-6">{answer}</p>}</div>)}</div></div></section>

      <section className="border-b border-white/10 bg-orange-500 text-black"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><h2 className="max-w-3xl text-4xl font-black tracking-[-.04em] sm:text-6xl">Siap menggunakan KerjaHarian?</h2><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => go('employer')} className="rounded-xl bg-black px-7 py-3.5 text-sm font-black text-white">BUTUH PEKERJA</button><button type="button" onClick={() => go('worker')} className="rounded-xl border border-black/20 px-7 py-3.5 text-sm font-black">CARI KERJA</button></div></div></section>

      <footer className="bg-[#050505]"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-10 md:grid-cols-4"><div><Logo className="[&_span]:text-white [&_.text-slate-400]:text-white/50"/><p className="mt-4 max-w-xs text-sm leading-6 text-white/40">Marketplace tenaga kerja harian.</p></div><div><p className="text-sm font-black">KerjaHarian</p><div className="mt-4 space-y-2 text-sm text-white/45"><button type="button" onClick={() => scrollTo('how')} className="block">Cara Kerja</button><button type="button" onClick={() => scrollTo('services')} className="block">Layanan</button><button type="button" onClick={() => go('help')} className="block">Pusat Bantuan</button></div></div><div><p className="text-sm font-black">Bergabung</p><div className="mt-4 space-y-2 text-sm text-white/45"><button type="button" onClick={() => go('employer')} className="block">Pemberi Kerja</button><button type="button" onClick={() => go('worker')} className="block">Pekerja</button></div></div><div><p className="text-sm font-black">Legal</p><div className="mt-4 space-y-2 text-sm text-white/45"><button type="button" onClick={() => go('terms')} className="block">Syarat & Ketentuan</button><button type="button" onClick={() => go('privacy')} className="block">Kebijakan Privasi</button></div></div></div><div className="mt-10 flex flex-col gap-5 border-t border-white/10 pt-6 text-xs text-white/30 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-x-4 gap-y-2">{socials.map(s => <span key={s}>{s}</span>)}</div><div className="flex items-center gap-4"><button type="button" onClick={() => { localStorage.setItem('kerjaharian_lang', 'id'); window.location.reload(); }}>Indonesia</button><button type="button" onClick={() => { localStorage.setItem('kerjaharian_lang', 'en'); window.location.reload(); }}>English</button><span>© 2026 KerjaHarian</span></div></div></div></footer>
    </main>
  );
}
