import React from 'react';
import { calculateOrderPrice } from '../utils/pricingEngine';
import { Shield, Clock, MapPin, CheckCircle, ArrowRight } from 'lucide-react';
import type { View } from '@/lib/types';
interface LandingProps { onNavigate: (view: View) => void; lang: 'id' | 'en'; }
const faqs = [['Apakah pekerja harus punya CV?', 'Tidak. Daftar dengan nomor WhatsApp dan lengkapi data yang diperlukan.'], ['Apakah harga pekerjaan bisa dinegosiasikan?', 'Tidak. Harga ditentukan berdasarkan jenis pekerjaan yang tersedia sehingga biaya dapat diketahui sebelum order.'], ['Bagaimana pekerja mendapatkan order?', 'Pekerja menerima informasi pekerjaan sesuai ketersediaan dan area layanan. Tawaran order dapat diterima atau ditolak sesuai ketentuan.'], ['Apakah employer perlu verifikasi KTP?', 'Ya. Verifikasi identitas membantu menjaga keamanan dan kepercayaan di platform.'], ['Berapa lama pekerja merespons?', 'Waktu respons berbeda menurut lokasi, jenis pekerjaan, dan ketersediaan pekerja. Status order ditampilkan di platform.']];
export function Landing({ onNavigate, lang }: LandingProps) { const samplePricing = calculateOrderPrice({ wageAmount: 250000, nightShift: true, needsTools: true }); return <div className="space-y-12 pb-24">
<section className="relative overflow-hidden bg-gradient-to-b from-primary-900 to-primary-950 px-4 py-14 text-white sm:py-16"><div className="mx-auto max-w-4xl space-y-6 text-center"><span className="inline-block rounded-full bg-primary-800 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-primary-200">{lang === 'id' ? 'Platform Kerja Harian Indonesia' : 'Indonesia Daily Work Platform'}</span><h1 className="text-3xl font-extrabold leading-tight tracking-tight sm:text-5xl">{lang === 'id' ? 'Butuh kerja hari ini? Atau butuh pekerja?' : 'Need work today? Or need a worker?'}</h1><p className="mx-auto max-w-2xl text-sm text-slate-300 sm:text-base">{lang === 'id' ? 'KerjaHarian menghubungkan pekerja harian dengan pemberi kerja melalui proses yang sederhana, harga yang jelas, dan pembayaran online.' : 'KerjaHarian connects daily workers and employers with a simple process, clear pricing, and online payment.'}</p><div className="flex flex-col justify-center gap-3 pt-2 sm:flex-row"><button onClick={() => onNavigate('worker')} className="flex items-center justify-center gap-2 rounded-xl bg-green-600 px-6 py-3 text-sm font-bold text-white shadow-lg hover:bg-green-700">Saya Cari Kerja <ArrowRight className="h-4 w-4" /></button><button onClick={() => onNavigate('employer')} className="flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/10 px-6 py-3 text-sm font-bold text-white hover:bg-white/20">Saya Cari Pekerja <ArrowRight className="h-4 w-4" /></button></div></div></section>
<section className="mx-auto grid max-w-6xl grid-cols-1 gap-6 px-4 md:grid-cols-3"><div className="space-y-3 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><CheckCircle className="h-5 w-5 text-primary-600"/><h2 className="font-bold text-slate-900">Harga Jelas</h2><p className="text-xs leading-relaxed text-slate-600">Harga mengikuti jenis pekerjaan. Tidak perlu tawar-menawar manual.</p></div><div className="space-y-3 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><Clock className="h-5 w-5 text-primary-600"/><h2 className="font-bold text-slate-900">Proses Sederhana</h2><p className="text-xs leading-relaxed text-slate-600">Masuk menggunakan WhatsApp dan ikuti langkah yang ditampilkan di layar.</p></div><div className="space-y-3 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><Shield className="h-5 w-5 text-primary-600"/><h2 className="font-bold text-slate-900">Lebih Aman</h2><p className="text-xs leading-relaxed text-slate-600">Employer melalui proses verifikasi identitas dan pembayaran diproses melalui kanal resmi.</p></div></section>
<section className="mx-auto max-w-xl px-4"><div className="space-y-4 rounded-2xl border bg-white p-6 shadow-md"><div className="flex items-center justify-between"><span className="rounded-md bg-primary-50 px-2.5 py-1 text-xs font-bold uppercase tracking-wider text-primary-700">Contoh Kalkulasi</span><span className="text-xs font-semibold text-emerald-600">Harga transparan</span></div><h2 className="font-bold text-slate-900 text-sm">Tukang Renovasi — Shift Malam + Alat</h2><div className="space-y-2 rounded-xl border bg-slate-50 p-3.5 text-xs text-slate-600"><div className="flex justify-between"><span>Upah dasar</span><span>Rp {samplePricing.wageAmount.toLocaleString('id-ID')}</span></div>{samplePricing.nightShiftAdd > 0 && <div className="flex justify-between"><span>Shift malam</span><span>+ Rp {samplePricing.nightShiftAdd.toLocaleString('id-ID')}</span></div>}{samplePricing.toolAllowance > 0 && <div className="flex justify-between"><span>Alat</span><span>+ Rp {samplePricing.toolAllowance.toLocaleString('id-ID')}</span></div>}<div className="flex justify-between"><span>Biaya platform</span><span>+ Rp {samplePricing.platformFee.toLocaleString('id-ID')}</span></div><div className="flex justify-between"><span>Asuransi</span><span>+ Rp {samplePricing.insurance.microInsurance.toLocaleString('id-ID')}</span></div><div className="flex justify-between border-t pt-2 text-sm font-bold text-slate-900"><span>Total</span><span className="text-green-600">Rp {samplePricing.totalPrice.toLocaleString('id-ID')}</span></div></div><button onClick={() => onNavigate('employer')} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 py-2.5 text-xs font-bold text-white hover:bg-slate-800">Mulai Pesan Pekerja <ArrowRight className="h-3.5 w-3.5" /></button></div></section>
<section className="mx-auto max-w-4xl px-4"><div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-2"><MapPin className="h-5 w-5 text-primary-600"/><h2 className="text-xl font-extrabold text-slate-900">Cara kerja KerjaHarian</h2></div><div className="grid gap-5 sm:grid-cols-3"><div><b>1. Pilih</b><p className="mt-1 text-sm text-slate-600">Pilih kebutuhan kerja atau pekerjaan yang tersedia.</p></div><div><b>2. Order</b><p className="mt-1 text-sm text-slate-600">Lihat detail dan harga sebelum melanjutkan.</p></div><div><b>3. Selesaikan</b><p className="mt-1 text-sm text-slate-600">Ikuti status order sampai pekerjaan selesai.</p></div></div></div></section>
<section className="mx-auto max-w-4xl px-4"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold text-slate-900">Pertanyaan yang sering ditanyakan</h2><div className="mt-4 space-y-2">{faqs.map(([q,a]) => <details key={q} className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-bold text-slate-900">{q}</summary><p className="mt-2 text-sm leading-6 text-slate-600">{a}</p></details>)}</div><button onClick={() => onNavigate('help')} className="mt-5 text-sm font-bold text-primary-700 hover:underline">Lihat semua bantuan →</button></div></section>
<div className="fixed inset-x-0 bottom-0 z-40 border-t border-slate-200 bg-white/95 p-2 shadow-2xl backdrop-blur sm:hidden"><div className="mx-auto flex max-w-lg gap-2"><button onClick={() => onNavigate('worker')} className="flex-1 rounded-xl bg-slate-900 py-3 text-xs font-extrabold text-white">🔎 Cari Kerja</button><button onClick={() => onNavigate('employer')} className="flex-1 rounded-xl bg-green-600 py-3 text-xs font-extrabold text-white">👷 Cari Pekerja</button></div></div>
</div>; }
