import { useCallback, useEffect, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, BriefcaseBusiness, CheckCircle2, Clock3, DollarSign, Lightbulb, RefreshCw, ShieldAlert, Users, UserRoundCheck, UserRoundPlus, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type JobKpiRow={id:string;employer_id:string|null;worker_id:string|null;status:string|null;workflow_status:string|null;payment_status:string|null;created_at:string;completed_at:string|null;paid_at:string|null;worker_amount:number|null;midtrans_transaction_status:string|null};
type ProfileKpiRow={role:string|null;is_online:boolean|null};
type Point={date:string;label:string;published:number;filled:number;completed:number;paid:number;income:number};
type Metrics={activeWorkers:number;activeEmployers:number;jobsToday:number;publishedJobs:number;filledJobs:number;completedJobs:number;paidJobs:number;workerIncome:number;repeatEmployers:number;reports:number;fillRate:number|null;completionRate:number|null;jobToIncome:number|null;points:Point[]};
type Insight={priority:string;title:string;reason:string;action:string};
const emptyMetrics:Metrics={activeWorkers:0,activeEmployers:0,jobsToday:0,publishedJobs:0,filledJobs:0,completedJobs:0,paidJobs:0,workerIncome:0,repeatEmployers:0,reports:0,fillRate:null,completionRate:null,jobToIncome:null,points:[]};
const money=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
const pct=(v:number|null)=>v===null?'—':`${Math.round(v*100)}%`;
const filled=(j:JobKpiRow)=>j.worker_id!==null||['assigned','worker_checked_in','employer_checked_in','ready_to_start','active','overtime','completed'].includes(j.workflow_status??'');
const completed=(j:JobKpiRow)=>j.status==='completed'||j.workflow_status==='completed';
const paid=(j:JobKpiRow)=>completed(j)&&(j.payment_status==='settled'||j.paid_at!==null||['settlement','capture'].includes(j.midtrans_transaction_status??''));
function buildPoints(rows:JobKpiRow[],days:number){const now=new Date();const start=new Date(now);start.setHours(0,0,0,0);start.setDate(start.getDate()-(days-1));const map=new Map<string,Point>();for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10);map.set(key,{date:key,label:d.toLocaleDateString('id-ID',{day:'2-digit',month:'short'}),published:0,filled:0,completed:0,paid:0,income:0});}for(const j of rows){const p=map.get(j.created_at.slice(0,10));if(!p)continue;p.published++;if(filled(j))p.filled++;if(completed(j))p.completed++;if(paid(j)){p.paid++;p.income+=Number(j.worker_amount??0);}}return [...map.values()];}
function SvgTrend({points,metric}:{points:Point[];metric:keyof Pick<Point,'published'|'filled'|'completed'|'paid'|'income'>}){const width=720,height=220,pad=28,max=Math.max(1,...points.map(p=>Number(p[metric])));const pts=points.map((p,i)=>{const x=pad+(i*Math.max(1,width-pad*2))/(Math.max(1,points.length-1));const y=height-pad-(Number(p[metric])/max)*(height-pad*2);return{x,y,v:Number(p[metric]),label:p.label};});const line=pts.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' ');return <div className="overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-56 min-w-[640px] w-full" role="img" aria-label={`Trend ${metric}`}><path d={`M ${pad} ${height-pad} H ${width-pad}`} stroke="currentColor" strokeOpacity=".12"/><path d={line} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{pts.map((p,i)=><g key={`${p.label}-${i}`}><circle cx={p.x} cy={p.y} r="5" fill="currentColor" className="cursor-help"><title>{`${p.label}: ${metric==='income'?money(p.v):p.v}`}</title></circle>{(i===0||i===pts.length-1||i%Math.max(1,Math.ceil(pts.length/6))===0)&&<text x={p.x} y={height-7} textAnchor="middle" fontSize="10" fill="currentColor" opacity=".65">{p.label}</text>}</g>)}</svg></div>}
export default function MarketplaceKpiPanel(){
 const [period,setPeriod]=useState<7|14|30>(7);const [metric,setMetric]=useState<'published'|'filled'|'completed'|'paid'|'income'>('published');const [metrics,setMetrics]=useState<Metrics>(emptyMetrics);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState('');const [insights,setInsights]=useState<Insight[]>([]);const [aiSummary,setAiSummary]=useState('');const [aiDirection,setAiDirection]=useState<'naik'|'turun'|'stabil'>('stabil');const [aiLoading,setAiLoading]=useState(false);
 const load=useCallback(async(days=period,withAi=true)=>{setLoading(true);setNotice('');const now=new Date();const start=new Date(now);start.setHours(0,0,0,0);start.setDate(start.getDate()-(days*2-1));const [profiles,jobs,reports]=await Promise.all([supabase.from('profiles').select('role,is_online'),supabase.from('jobs').select('id,employer_id,worker_id,status,workflow_status,payment_status,created_at,completed_at,paid_at,worker_amount,midtrans_transaction_status').eq('is_deleted',false).gte('created_at',start.toISOString()),supabase.from('job_reports').select('id',{count:'exact',head:true})]);const error=profiles.error??jobs.error??reports.error;if(error){setNotice(`KPI belum dapat dimuat: ${error.message}`);setLoading(false);return;}const all=(jobs.data??[]) as JobKpiRow[];const currentStart=new Date(now);currentStart.setHours(0,0,0,0);currentStart.setDate(currentStart.getDate()-(days-1));const current=all.filter(j=>new Date(j.created_at)>=currentStart);const previousStart=new Date(currentStart);previousStart.setDate(previousStart.getDate()-days);const previous=all.filter(j=>{const d=new Date(j.created_at);return d>=previousStart&&d<currentStart;});const completedRows=current.filter(completed);const paidRows=current.filter(paid);const employerCompletions=new Map<string,number>();for(const j of completedRows)if(j.employer_id)employerCompletions.set(j.employer_id,(employerCompletions.get(j.employer_id)??0)+1);const fill=current.filter(filled).length;const completion=completedRows.length;const paidCount=paidRows.length;const jobGrowth=previous.length===0?(current.length>0?1:null):(current.length-previous.length)/previous.length;const todayStart=new Date(now);todayStart.setHours(0,0,0,0);const next:Metrics={activeWorkers:(profiles.data??[]).filter((p:ProfileKpiRow)=>p.role==='worker'&&p.is_online===true).length,activeEmployers:(profiles.data??[]).filter((p:ProfileKpiRow)=>p.role==='employer'&&p.is_online===true).length,jobsToday:current.filter(j=>new Date(j.created_at)>=todayStart).length,publishedJobs:current.length,filledJobs:fill,completedJobs:completion,paidJobs:paidCount,workerIncome:paidRows.reduce((s,j)=>s+Number(j.worker_amount??0),0),repeatEmployers:[...employerCompletions.values()].filter(n=>n>=2).length,reports:reports.count??0,fillRate:current.length?fill/current.length:null,completionRate:fill?completion/fill:null,jobToIncome:current.length?paidCount/current.length:null,points:buildPoints(current,days)};setMetrics(next);setLoading(false);
 if(withAi){setAiLoading(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){setAiSummary('Login admin diperlukan untuk analisis AI.');setInsights([]);}else{const res=await fetch('/api/ai-admin-insights',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify({metrics:{period_days:days,published_jobs:current.length,filled_jobs:fill,completed_jobs:completion,paid_jobs:paidCount,fill_rate:next.fillRate,completion_rate:next.completionRate,dispute_rate:null,no_show_rate:null,job_growth:jobGrowth,worker_income:next.workerIncome}})});const data=await res.json();if(!res.ok)throw new Error(data?.error||'Analisis AI gagal');setAiSummary(data.summary||'Analisis tersedia.');setAiDirection(data.direction||'stabil');setInsights(Array.isArray(data.recommendations)?data.recommendations:[]);}}catch(e){setAiSummary(e instanceof Error?e.message:'Analisis AI gagal dimuat.');setInsights([]);}finally{setAiLoading(false);}}
 },[period]);
 useEffect(()=>{void load(period);const timer=window.setInterval(()=>{void load(period,true)},15*60*1000);return()=>window.clearInterval(timer);},[period,load]);
 const cards=[['Active Workers',metrics.activeWorkers,Users],['Active Employers',metrics.activeEmployers,BriefcaseBusiness],['Jobs Today',metrics.jobsToday,BriefcaseBusiness],['Jobs Filled',metrics.filledJobs,UserRoundCheck],['Match / Fill Rate',pct(metrics.fillRate),Activity],['Completion Rate',pct(metrics.completionRate),CheckCircle2],['Paid Jobs',metrics.paidJobs,DollarSign],['Worker Income',money(metrics.workerIncome),DollarSign],['Repeat Employers',metrics.repeatEmployers,UserRoundPlus],['Reports / Incidents',metrics.reports,ShieldAlert],['Published Jobs',metrics.publishedJobs,BriefcaseBusiness],['Job → Income',pct(metrics.jobToIncome),CheckCircle2]] as const;
 const trendLabel={published:'Jobs published',filled:'Jobs filled',completed:'Jobs completed',paid:'Paid jobs',income:'Worker income'}[metric];const DirectionIcon=aiDirection==='naik'?ArrowUpRight:aiDirection==='turun'?ArrowDownRight:Activity;
 return <section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200" aria-label="Marketplace KPI Command Center"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Activity className="h-5 w-5"/><h2 className="font-extrabold">Marketplace KPI Command Center</h2></div><p className="mt-1 text-xs text-slate-500">KPI, trend interaktif, dan analisis AI berbasis data marketplace nyata. Tidak membuat data sintetis. AI otomatis diperbarui setiap 15 menit saat panel terbuka.</p></div><button onClick={()=>void load(period,true)} disabled={loading||aiLoading} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-50"><RefreshCw className={`h-3.5 w-3.5 ${loading||aiLoading?'animate-spin':''}`}/>Sync & Analisis</button></div>
 <div className="mb-5 flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-slate-500">Periode</span>{([7,14,30] as const).map(d=><button key={d} onClick={()=>setPeriod(d)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ring-1 ${period===d?'bg-slate-900 text-white ring-slate-900':'bg-white text-slate-600 ring-slate-200'}`}>{d} hari</button>)}</div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon])=><div key={label} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold text-slate-500">{label}</span><Icon className="h-4 w-4 text-slate-400"/></div><div className="mt-2 text-xl font-black">{loading?'—':value}</div></div>)}</div>
 <div className="mt-5 rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-extrabold">Trend {trendLabel}</h3><p className="text-xs text-slate-500">Hover titik untuk nilai harian. Periode mengikuti pilihan di atas.</p></div><select value={metric} onChange={e=>setMetric(e.target.value as typeof metric)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold"><option value="published">Jobs published</option><option value="filled">Jobs filled</option><option value="completed">Jobs completed</option><option value="paid">Paid jobs</option><option value="income">Worker income</option></select></div>{loading?<div className="flex h-56 items-center justify-center text-sm text-slate-400">Memuat trend…</div>:metrics.points.length?<SvgTrend points={metrics.points} metric={metric}/>:<div className="flex h-56 items-center justify-center text-sm text-slate-400">Belum ada data trend.</div>}</div>
 <div className="mt-5 rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Lightbulb className="h-5 w-5"/><h3 className="font-extrabold">AI Admin Briefing</h3></div><p className="mt-1 text-xs text-slate-500">Arah pertumbuhan dan tindakan prioritas untuk periode {period} hari.</p></div><div className="inline-flex items-center gap-1 rounded-full bg-slate-50 px-3 py-1 text-xs font-black ring-1 ring-slate-200"><DirectionIcon className="h-3.5 w-3.5"/>{aiDirection}</div></div>{aiLoading?<div className="mt-4 text-sm text-slate-500">AI sedang menganalisis KPI…</div>:<><p className="mt-4 text-sm font-semibold text-slate-700">{aiSummary||'Belum ada briefing.'}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{insights.map((i,n)=><div key={`${i.title}-${n}`} className="rounded-xl bg-slate-50 p-4 ring-1 ring-slate-200"><div className="flex items-center justify-between gap-2"><h4 className="font-extrabold">{i.title}</h4><span className="text-[10px] font-black uppercase text-slate-500">{i.priority}</span></div><p className="mt-1 text-xs text-slate-600">{i.reason}</p><p className="mt-2 text-xs font-bold text-slate-700">Tindakan: {i.action}</p></div>)}</div></>}</div>
 {!loading&&metrics.publishedJobs===0&&<div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-600"><Clock3 className="h-4 w-4"/>Belum ada data transaksi pada periode ini. Chart tetap jujur menampilkan nol dan AI tidak mengarang performa.</div>}{!loading&&metrics.publishedJobs>0&&metrics.paidJobs===0&&<div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-600"><XCircle className="h-4 w-4"/>Belum ada job yang teridentifikasi settled/paid; income tidak diasumsikan dari nilai job.</div>}{notice&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800 ring-1 ring-amber-200">{notice}</div>}</section>;
}
