import { ArrowLeft, ChevronDown, MessageCircle, ShieldCheck } from 'lucide-react';
import type { View } from '@/lib/types';

interface Props { view: 'privacy' | 'terms' | 'help'; onNavigate: (view: View) => void; }
const faqs = [
  ['Apakah pekerja harus punya CV?', 'Tidak. Kamu daftar menggunakan nomor WhatsApp dan melengkapi data yang diperlukan.'],
  ['Apakah harga pekerjaan bisa dinegosiasikan?', 'Tidak. KerjaHarian menggunakan harga yang ditentukan untuk jenis pekerjaan yang tersedia sehingga harga dapat diketahui sebelum order.'],
  ['Bagaimana pekerja mendapatkan order?', 'Pekerja menerima informasi pekerjaan sesuai ketersediaan dan area layanan, lalu dapat menerima atau menolaknya sesuai ketentuan order.'],
  ['Apakah employer perlu verifikasi identitas?', 'Ya. Verifikasi identitas merupakan bagian dari upaya menjaga keamanan dan kepercayaan di platform.'],
  ['Bagaimana kalau terjadi masalah dengan pekerjaan?', 'Hubungi CS KerjaHarian dan siapkan ID order serta bukti pembayaran agar tim dapat memeriksa kasusnya.'],
];
export default function PublicInfoPage({ view, onNavigate }: Props) {
  const title = view === 'privacy' ? 'Kebijakan Privasi' : view === 'terms' ? 'Syarat & Ketentuan' : 'Pusat Bantuan';
  return <section className="mx-auto max-w-3xl px-4 py-10 sm:py-14">
    <button onClick={() => onNavigate('landing')} className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-900"><ArrowLeft className="h-4 w-4" /> Kembali ke Beranda</button>
    <div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-10">
      <div className="flex items-start gap-4"><div className="rounded-2xl bg-primary-50 p-3 text-primary-700"><ShieldCheck className="h-6 w-6" /></div><div><h1 className="text-2xl font-extrabold text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-500">KerjaHarian • informasi resmi layanan</p></div></div>
      {view === 'help' && <div className="mt-8 space-y-3">{faqs.map(([q,a]) => <details key={q} className="rounded-2xl border border-slate-200 p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-slate-900"><span>{q}</span><ChevronDown className="h-4 w-4" /></summary><p className="mt-3 text-sm leading-6 text-slate-600">{a}</p></details>)}<a href="https://wa.me/6288289767019" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-green-600 px-4 py-3 text-sm font-bold text-white hover:bg-green-700"><MessageCircle className="h-4 w-4" /> Chat WhatsApp CS</a></div>}
      {view === 'privacy' && <div className="mt-8 space-y-6 text-sm leading-7 text-slate-600"><div><h2 className="font-extrabold text-slate-900">1. Data yang kami kumpulkan</h2><p>KerjaHarian dapat memproses nomor WhatsApp, data profil, data identitas untuk verifikasi, informasi pekerjaan, lokasi yang diperlukan untuk layanan, serta informasi transaksi dan pembayaran.</p></div><div><h2 className="font-extrabold text-slate-900">2. Penggunaan data</h2><p>Data digunakan untuk akun, keamanan, order, verifikasi, pencocokan pekerjaan, pencegahan penyalahgunaan, pembayaran, dan bantuan pengguna.</p></div><div><h2 className="font-extrabold text-slate-900">3. Data KTP</h2><p>Data identitas digunakan untuk proses verifikasi sesuai kebutuhan layanan. Akses dibatasi sesuai fungsi dan kebutuhan keamanan. Jangan kirim KTP melalui chat publik.</p></div><div><h2 className="font-extrabold text-slate-900">4. Keamanan dan hak pengguna</h2><p>Kami menerapkan pengamanan teknis dan organisasi yang wajar. Untuk pertanyaan atau permintaan terkait data pribadi, hubungi CS melalui kanal resmi KerjaHarian.</p></div><div><h2 className="font-extrabold text-slate-900">5. Perubahan kebijakan</h2><p>Kebijakan dapat diperbarui ketika layanan atau ketentuan hukum berubah. Versi terbaru dipublikasikan di halaman ini.</p></div></div>}
      {view === 'terms' && <div className="mt-8 space-y-6 text-sm leading-7 text-slate-600"><div><h2 className="font-extrabold text-slate-900">1. Penggunaan layanan</h2><p>Pengguna wajib memberikan informasi yang benar, menjaga akses akun, dan menggunakan KerjaHarian hanya untuk kebutuhan kerja yang sah.</p></div><div><h2 className="font-extrabold text-slate-900">2. Harga dan pembayaran</h2><p>Harga ditampilkan berdasarkan jenis pekerjaan dan ketentuan yang berlaku saat order. Pembayaran dilakukan melalui metode yang disediakan KerjaHarian.</p></div><div><h2 className="font-extrabold text-slate-900">3. Order dan pembatalan</h2><p>Status order mengikuti proses di platform. Pembatalan, pengembalian dana, atau perubahan order mengikuti ketentuan pada transaksi terkait.</p></div><div><h2 className="font-extrabold text-slate-900">4. Kewajiban</h2><p>Pekerja wajib menjalankan pekerjaan sesuai detail order. Employer wajib memberikan informasi pekerjaan yang benar, lokasi yang aman, dan kondisi kerja sesuai detail order.</p></div><div><h2 className="font-extrabold text-slate-900">5. Larangan</h2><p>Dilarang melakukan penipuan, penyalahgunaan identitas, pelecehan, transaksi yang melanggar ketentuan platform, atau aktivitas melanggar hukum. KerjaHarian dapat membatasi atau menonaktifkan akun sesuai hasil pemeriksaan.</p></div><div><h2 className="font-extrabold text-slate-900">6. Bantuan dan sengketa</h2><p>Untuk masalah transaksi, segera hubungi CS dengan ID order dan bukti terkait. KerjaHarian akan memeriksa berdasarkan data yang tersedia.</p></div></div>}
    </div>
  </section>;
}
