import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ShieldAlert } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';

type JobOption={id:string;title:string|null;status:string|null;worker_id:string|null;employer_id:string|null;order_id:string|null};
type Incident={id:string;job_id:string;incident_type:string;severity:string;description:string;status:string;created_at:string};
const TYPES=[['injury','Cedera / kecelakaan'],['threat','Ancaman'],['violence','Kekerasan'],['unsafe_condition','Kondisi tidak aman'],['scope_violation','Pelanggaran lingkup kerja'],['payment_issue','Masalah pembayaran'],['other','Lainnya']] as const;
const SEVERITIES=[['low','Rendah'],['medium','Sedang'],['high','Tinggi'],['critical','Kritis']] as const;

export function SafetyIncidentCenter(){
 const{user,profile}=useAuth();
 const[jobs,setJobs]=useState<JobOption[]>([]);const[incidents,setIncidents]=useState<Incident[]>([]);const[jobId,setJobId]=useState('');const[type,setType]=useState('unsafe_condition');const[severity,setSeverity]=useState('medium');const[description,setDescription]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
 const load=useCallback(async()=>{if(!user)return;const[j,e]=await Promise.all([supabase.from('jobs').select('id,title,status,worker_id,employer_id,order_id').or(`worker_id.eq.${user.id},employer_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(30),supabase.from('job_incidents').select('id,job_id,incident_type,severity,description,status,created_at').eq('reported_by',user.id).order('created_at',{ascending:false}).limit(20)]);if(j.error||e.error){setError('Data insiden tidak dapat dimuat.');return}setJobs((j.data??[]) as JobOption[]);setIncidents((e.data??[]) as Incident[])},[user]);
 useEffect(()=>{void load()},[load]);
 const submit=async()=>{if(!jobId){setError('Pilih pekerjaan.');return}const clean=description.trim();if(clean.length<10){setError('Jelaskan insiden minimal 10 karakter.');return}setBusy(true);setError('');setSuccess('');const{error:e}=await supabase.rpc('record_job_incident',{p_job_id:jobId,p_incident_type:type,p_severity:severity,p_description:clean});if(e)setError(e.message);else{setSuccess(severity==='critical'||severity==='high'?'Insiden dicatat dan ditandai untuk penanganan segera.':'Insiden berhasil dilaporkan ke pusat keselamatan.');setDescription('');setJobId('');await load()}setBusy(false)};
 if(!user||!profile)return null;
 return <section className="rounded-2xl border border-amber-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-700"><ShieldAlert className="h-5 w-5"/></div><div><h2 className="font-display font-bold text-slate-900">Laporkan masalah keselamatan</h2><p className="mt-1 text-xs leading-5 text-slate-500">Gunakan ini untuk cedera, ancaman, kekerasan, kondisi tidak aman, atau masalah serius saat pekerjaan.</p></div></div>{success&&<div className="mt-4 flex gap-2 rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4 shrink-0"/>{success}</div>}{error&&<div className="mt-4 flex gap-2 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700"><AlertTriangle className="h-4 w-4 shrink-0"/>{error}</div>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={jobId} onChange={e=>setJobId(e.target.value)} className="input"><option value="">Pilih pekerjaan...</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.title||'Pekerjaan'} · {j.status||'status'}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="input">{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)} className="input sm:col-span-2">{SEVERITIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><textarea value={description} onChange={e=>setDescription(e.target.value.slice(0,5000))} maxLength={5000} rows={4} className="input mt-3" placeholder="Jelaskan apa yang terjadi secara faktual, termasuk kondisi yang membuat pekerjaan tidak aman..."/><button disabled={busy||!jobId||description.trim().length<10} onClick={()=>void submit()} className="mt-3 min-h-11 w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy?'Menyimpan laporan...':'Laporkan Insiden'}</button>{incidents.length>0&&<div className="mt-5 border-t pt-4"><h3 className="text-xs font-extrabold text-slate-700">Laporan saya</h3><div className="mt-2 space-y-2">{incidents.map(i=><div key={i.id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-2 text-[10px] font-bold"><span>{TYPES.find(([v])=>v===i.incident_type)?.[1]||i.incident_type}</span><span>{i.status}</span></div><p className="mt-1 text-xs text-slate-600">{i.description}</p></div>)}</div></div>}</section>;
}