import { lazy, Suspense, useState, useCallback, useEffect } from 'react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { AuthModal } from '@/components/AuthModal';
import { AppErrorBoundary } from '@/components/AppErrorBoundary';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { AIProblemSolver } from '@/components/AIProblemSolver';
import { AIVoiceAssistant } from '@/components/AIVoiceAssistant';
import { PWAInstallPrompt } from '@/components/PWAInstallPrompt';
import { EmployerRematchPanel } from '@/components/EmployerRematchPanel';
import { EmployerMatchingControl } from '@/components/EmployerMatchingControl';
import { WorkerConfirmationStatus } from '@/components/WorkerConfirmationStatus';
import { WorkerMatchingProfile } from '@/components/WorkerMatchingProfile';
import { I18n } from '@/lib/i18n';
import { useAuth } from '@/lib/auth';
import type { View, CategoryId } from '@/lib/types';
const Landing = lazy(() => import('@/components/LandingDark').then(m => ({ default: m.LandingDark })));
const EmployerEntry = lazy(() => import('@/components/EmployerEntry').then(m => ({ default: m.EmployerEntry })));
const Worker = lazy(() => import('@/components/Worker').then(m => ({ default: m.Worker })));
const ResolutionCenter = lazy(() => import('@/components/ResolutionCenter').then(m => ({ default: m.ResolutionCenter })));
const SafetyIncidentCenter = lazy(() => import('@/components/SafetyIncidentCenter').then(m => ({ default: m.SafetyIncidentCenter })));
const AdminResolutionQueue = lazy(() => import('@/components/AdminResolutionQueue'));
const AdminIncidentQueue = lazy(() => import('@/components/AdminIncidentQueue'));
const AdminPrivacyQueue = lazy(() => import('@/components/AdminPrivacyQueue'));
const AdminLogin = lazy(() => import('@/components/AdminLogin'));
const AdminRoute = lazy(() => import('@/components/AdminRoute'));
const AdminDashboard = lazy(() => import('@/components/AdminDashboard'));
const KycGate = lazy(() => import('@/components/KycGate'));
const JobTimer = lazy(() => import('@/components/JobTimer').then(m => ({ default: m.JobTimer })));
const OvertimeApprovalPanel = lazy(() => import('@/components/OvertimeApprovalPanel').then(m => ({ default: m.OvertimeApprovalPanel })));
const PrivacyCenter = lazy(() => import('@/components/PrivacyCenter').then(m => ({ default: m.PrivacyCenter })));
const WorkerDispatchPanel = lazy(() => import('@/components/OnDemandDispatch').then(m => ({ default: m.WorkerDispatchPanel })));
const EmployerDispatchWatcher = lazy(() => import('@/components/OnDemandDispatch').then(m => ({ default: m.EmployerDispatchWatcher })));
const PublicInfoPage = lazy(() => import('@/components/PublicInfoPage'));
const NotFoundPage = lazy(() => import('@/components/NotFoundPage'));
const SECRET_PATH = '/rahasia';
const ADMIN_RESOLUTION_PATH = '/admin/resolutions';
const ADMIN_INCIDENT_PATH = '/admin/incidents';
const ADMIN_PRIVACY_PATH = '/admin/privacy';
const ADMIN_PREVIEW_PARAM = 'admin-preview';