create table if not exists public.fonnte_device_status (
  id bigint generated by default as identity primary key,
  device text not null,
  status text not null check (status in ('connect','disconnect','unknown')),
  reason text,
  source text not null default 'webhook' check (source in ('webhook','healthcheck')),
  event_at timestamptz not null default now(),
  checked_at timestamptz not null default now(),
  raw jsonb,
  created_at timestamptz not null default now()
);
create index if not exists fonnte_device_status_device_event_idx on public.fonnte_device_status(device,event_at desc);
create table if not exists public.fonnte_monitor_config (
  id boolean primary key default true check (id),
  webhook_secret text not null default encode(gen_random_bytes(32),'hex'),
  health_secret text not null default encode(gen_random_bytes(32),'hex'),
  device text,
  last_status text not null default 'unknown' check (last_status in ('connect','disconnect','unknown')),
  last_reason text,
  last_event_at timestamptz,
  last_health_check_at timestamptz,
  consecutive_failures integer not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.fonnte_monitor_config (id) values (true) on conflict (id) do nothing;
alter table public.otp_codes add column if not exists code_hash text;
alter table public.otp_codes add column if not exists attempts integer not null default 0;
alter table public.otp_codes add column if not exists sent_at timestamptz;
alter table public.otp_codes add column if not exists provider_status text;
alter table public.otp_codes add column if not exists provider_detail text;
create index if not exists otp_codes_phone_created_idx on public.otp_codes(phone,created_at desc);
alter table public.fonnte_device_status enable row level security;
alter table public.fonnte_monitor_config enable row level security;
revoke all on public.fonnte_device_status from anon, authenticated;
revoke all on public.fonnte_monitor_config from anon, authenticated;
create or replace function public.fonnte_monitor_snapshot()
returns jsonb language sql security definer set search_path = public as $$
  select jsonb_build_object('status',c.last_status,'reason',c.last_reason,'device',c.device,'last_event_at',c.last_event_at,'last_health_check_at',c.last_health_check_at,'consecutive_failures',c.consecutive_failures)
  from public.fonnte_monitor_config c where c.id=true;
$$;
revoke all on function public.fonnte_monitor_snapshot() from public, anon;
grant execute on function public.fonnte_monitor_snapshot() to authenticated;
create or replace function public.consume_fonnte_otp(p_phone text, p_code_hash text)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
  select id into v_id from public.otp_codes where phone=p_phone and used=false and expired_at>now() and (code_hash=p_code_hash or (code_hash is null and code=p_code_hash)) order by created_at desc limit 1 for update;
  if v_id is null then
    update public.otp_codes set attempts=attempts+1 where phone=p_phone and used=false and expired_at>now();
    return false;
  end if;
  update public.otp_codes set used=true, attempts=attempts+1 where id=v_id;
  return true;
end; $$;
revoke all on function public.consume_fonnte_otp(text,text) from public, anon, authenticated;
create or replace function public.record_fonnte_health_failure(p_reason text)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.fonnte_monitor_config set last_status='unknown', last_reason=left(coalesce(p_reason,'unknown'),500), last_health_check_at=now(), consecutive_failures=consecutive_failures+1, updated_at=now() where id=true;
  insert into public.fonnte_device_status(device,status,reason,source,event_at,checked_at,raw) values ('unknown','unknown',left(coalesce(p_reason,'unknown'),500),'healthcheck',now(),now(),jsonb_build_object('error',p_reason));
end; $$;
revoke all on function public.record_fonnte_health_failure(text) from public, anon, authenticated;
